### ISSUE TITLE
issue on connecting

### ISSUE THREAD

**Issue by woshka** [schwabe/ics-openvpn#1051]
hello,
I have the following issue when connecting to a profile

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blinkt.openvpn, PID: 6429
    java.lang.NoClassDefFoundError: de.blinkt.openvpn.core.NativeUtils
        at de.blinkt.openvpn.core.NativeUtils.getNativeAPI(NativeUtils.java:21)
        at de.blinkt.openvpn.core.VpnStatus.logInformation(VpnStatus.java:241)
        at de.blinkt.openvpn.core.VpnStatus.clearLog(VpnStatus.java:233)
        at de.blinkt.openvpn.LaunchVPN.startVpnFromIntent(LaunchVPN.java:135)
        at de.blinkt.openvpn.LaunchVPN.onCreate(LaunchVPN.java:94)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.blinkt.openvpn-BAWnONCCh0N7a3uXn2OZWQ==/base.apk"],nativeLibraryDirectories=[/data/app/de.blinkt.openvpn-BAWnONCCh0N7a3uXn2OZWQ==/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libopvpnutil.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at de.blinkt.openvpn.core.NativeUtils.<clinit>(NativeUtils.java:38)
        at de.blinkt.openvpn.core.NativeUtils.getNativeAPI(NativeUtils.java:21)
        at de.blinkt.openvpn.core.VpnStatus.logInformation(VpnStatus.java:241)
        at de.blinkt.openvpn.core.VpnStatus.<clinit>(VpnStatus.java:207)
        at de.blinkt.openvpn.core.VpnStatus.logError(VpnStatus.java:443)
        at de.blinkt.openvpn.api.AppRestrictions.applyRestrictions(AppRestrictions.java:88)
        at de.blinkt.openvpn.api.AppRestrictions.checkRestrictions(AppRestrictions.java:186)
        at de.blinkt.openvpn.core.ICSOpenVPNApplication.onCreate(ICSOpenVPNApplication.java:47)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
I/zygote: Do partial code cache collection, code=124KB, data=65KB
I/zygote: After code cache collection, code=123KB, data=65KB
    Increasing code cache capacity to 512KB
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by schwabe** [comment]
Looks like you are missing the native libraries, see README.

**Comment by woshka** [comment]
there were nothing for native liberaries on the readme
