### ISSUE TITLE
Error 13, Permission denied in Android 10

### ISSUE THREAD

**Issue by sanmish16** [schwabe/ics-openvpn#1084]
We are getting this issue in android 10:

**java.io.IOException: Cannot run program "/data/user/0/packageName/cache/c_pie_openvpn.arm64-v8a": error=13, Permission denied**

# General information
1. We are using AndroidX
3. Google Pixel
 
This issue is only in android 10 and on any other Android version, it's working fine. Our old app which is in play store is also working fine in Android 10.

**Comment by schwabe** [comment]
**/data/user/0/packageName/cache/c_pie_openvpn.arm64-v8a**

Please don't obfuscate logs. I feel you are obfuscating since you have a broken commercial app that does not work anymore.

**Comment by AfzalivE** [comment]
Okay but they're right, it is giving that error and it is broken on Android 10.

**Comment by dzolnai** [comment]
I can reproduce this issue in our EduVPN fork (currently matches v0.7.8) of this app when bumping the target SDK to 29.
At a first hunch I thought the cause might be the scoped-storage changes, but adding `android:requestLegacyExternalStorage="true"` to the manifest did not help fix the issue.

Here are the logs, from the view logs window:

```
2019-10-28 12:58:44 built by C=US,O=Android,CN=Android Debug 1.3 running on google Pixel 3 (blueline), Android 10 (QP1A.191005.007) API 29, ABI arm64-v8a, (google/blueline/blueline:10/QP1A.191005.007/5878874:user/release-keys)
2019-10-28 12:58:44 Building configuration…
2019-10-28 12:58:44 started Socket Thread
2019-10-28 12:58:44 Network Status: CONNECTED  to WIFI 
2019-10-28 12:58:44 Debug state info: CONNECTED  to WIFI , pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
2019-10-28 12:58:44 Error reading from output of OpenVPN process: Cannot run program "/data/user/0/nl.eduvpn.app/cache/c_pie_openvpn.arm64-v8a": error=13, Permission denied

java.io.IOException: Cannot run program "/data/user/0/nl.eduvpn.app/cache/c_pie_openvpn.arm64-v8a": error=13, Permission denied
 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
 at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:134)
 at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
 at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.IOException: error=13, Permission denied
 at java.lang.UNIXProcess.forkAndExec(Native Method)
 at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
 at java.lang.ProcessImpl.start(ProcessImpl.java:141)
 at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
 ... 3 more

2019-10-28 12:58:44 Starting OpenVPN Thread: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference
 at de.blinkt.openvpn.core.OpenVPNThread.stopProcess(OpenVPNThread.java:52)
 at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:193)
 at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
 at java.lang.Thread.run(Thread.java:919)

2019-10-28 12:58:44 Debug state info: CONNECTED  to WIFI , pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED
```

For now we will be sticking with target SDK set to 28.

**Comment by schwabe** [comment]
@dzolnai That is fixed in newer versions of ics-openvpn. EduVPN just needs to update its copy of ics-openvpn to the latest version and it will work again.

**Comment by dzolnai** [comment]
Okay, will do as soon there's a newer tagged version. Thanks for clearing it up!

**Comment by munkhbayar-gtk** [comment]
What is exactly the fix for this issue? I have a copy of this project from two years back. Now this copy is facing the same issue. using the latest version of ics-openvpn results in the much bigger app size. the app size is doubled.

I just want the fix porsion of the code and apply it into my copy

**Comment by schwabe** [comment]
@munkhbayar-gtk I have absolutely no interest in fixing old version of my app for free. Either you use the newest version of my app, pay for it or figure out yourself.

**Comment by mehroz1** [comment]
@dzolnai @sanmish16   Please refer to this 

https://github.com/schwabe/ics-openvpn/issues/1179#issuecomment-709324457

or

https://stackoverflow.com/a/64373156/7173141

I hope this will help you.

**Comment by schwabe** [comment]
@mehroz1 please stop spamming the bug tracker with that.

**Comment by mehroz1** [comment]
>  spamming the bug tracker with that.

@schwabe 

Sorry, I had no other choice every other fork on github is using ics-openvpn core which is written by you. So everyone was looking towards you but you were not helping. So after finding fix for this issue I took the liberty of replying everyone stuck on the same error.

**Comment by schwabe** [comment]
@mehroz1 There are very good reasons that I am not helping people that use outdated/insecure/buggy version of my software. As VPN software is security sensitive, there is no excuse in using old versions. You are actually now working against that goal by doing what you are doing.

**Comment by CRINOL** [comment]
@schwabe you are right. Been trying out this repo for days. Realised am using an old from 2018!
An upgrade to the latest version should fix my problem, thanks for the work @schwabe .
