### ISSUE TITLE
Generic problems building the app

### ISSUE THREAD

**Issue by Pecana** [schwabe/ics-openvpn#1112]
Hello, can you please add the x86 and x86_84 binary with the "pie" ?

**Comment by schwabe** [comment]
Could explain a bit more what error/problems you are seeing?

**Comment by Pecana** [comment]
The application provides the exectuable for armeabi-v7 and v8 but not for x86 and x86_84 devices. it will be nice to have also this file under assets and the .so lbraries

**Comment by schwabe** [comment]
@Pecana You need to provide more details. I cannot reproduce your problem.

**Comment by schwabe** [comment]
![image](https://user-images.githubusercontent.com/1038539/69642513-26157000-1062-11ea-8927-061999d4e7e3.png)
See the "Native Platformen", there is x86 and x86_64 right there and has been for almost as long as Android supported x86

**Comment by Pecana** [comment]
Then I guess my proleml is becasue if I clone the repository I can't open it on Android Studio :-(

**Comment by Pecana** [comment]
The doc/README is complelty useless :-( simply build will not generate the necessary files i was looking for

**Comment by schwabe** [comment]
Look at the .travis.yml file that also builds the whole project and works fine.

**Comment by uipko** [comment]
> Then I guess my proleml is becasue if I clone the repository I can't open it on Android Studio :-(

Did you try to import the project instead of open it with studio. This fixed some issue's for me. The import seems to do some magic based on the gradle files which I could not fix by manual changing settings.

**Comment by uipko** [comment]
> The doc/README is complelty useless :-( simply build will not generate the necessary files i was looking for

Following the README worked fine for me. Only thing I did different compared to the README was running ./gradlew build from project folder instead of gradle build. This way you make sure you're using the correct Gradle version.

Does ./gradlew build work without errors?
What files are you missing?

**Comment by Pecana** [comment]
> > The doc/README is complelty useless :-( simply build will not generate the necessary files i was looking for
> 
> Following the README worked fine for me. Only thing I did different compared to the README was running ./gradlew build from project folder instead of gradle build. This way you make sure you're using the correct Gradle version.
> 
> Does ./gradlew build work without errors?
> What files are you missing?

Hello, first of all trank you!
"gradle build" works without error but trying gradlew build failed:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':main:generateOpenVPN3Swig'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'swig''
        at org.gradle.process.internal.DefaultExecHandle.execExceptionFor(DefaultExecHandle.java:237)
        at org.gradle.process.internal.DefaultExecHandle.setEndStateInfo(DefaultExecHandle.java:214)
        at org.gradle.process.internal.DefaultExecHandle.failed(DefaultExecHandle.java:364)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:87)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        ... 3 more
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'swig'
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
        at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
        at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:98)
        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:71)
        ... 4 more
Caused by: java.io.IOException: Cannot run program "swig" (in directory "/home/pecana/cloni/ics-openvpn/main"): error=2, No such file or directory
        at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
        ... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
        ... 8 more
`

**Comment by schwabe** [comment]
`Cannot run program "swig" (in directory "/home/pecana/cloni/ics-openvpn/main"): error=2, No such file or directory`

The "completely useless README" tells you to install swig

**Comment by Pecana** [comment]
> `Cannot run program "swig" (in directory "/home/pecana/cloni/ics-openvpn/main"): error=2, No such file or directory`
> 
> The "completely useless README" tells you to install swig

My bad, it was after the (....) and I missed this, by the way it still does not work :-(


```14:44:58.006 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :main:assemble
14:44:58.006 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :main:assemble' started
14:44:58.007 [INFO] [com.android.build.gradle.internal.profile.RecordingBuildListener] Task :main:assemble in main Starting
14:44:58.007 [INFO] [org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter] Skipping task ':main:assemble' as it has no actions.
14:44:58.007 [INFO] [com.android.build.gradle.internal.profile.RecordingBuildListener] Task :main:assemble in main Finished
14:44:58.008 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :main:assemble'
14:44:58.008 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :main:assemble' completed
14:44:58.008 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :main:assemble (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
14:44:58.008 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on :
14:44:58.009 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.11 completed (1 worker(s) in use)
14:44:58.009 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on root.1.11
14:44:58.009 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': acquired lock on :
14:44:58.009 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.11 started (1 worker(s) in use).
14:44:58.010 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': acquired lock on root.1.11
14:44:58.010 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :main:lint (Thread[Execution worker for ':',5,main]) started.
14:44:58.010 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger]
14:44:58.010 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :main:lint FAILED
14:44:58.010 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :main:lint' started
14:44:58.010 [INFO] [com.android.build.gradle.internal.profile.RecordingBuildListener] Task :main:lint in main Starting
14:44:58.011 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':main:lint' into context took 0.0 secs.
14:44:58.011 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Removed task artifact state for {} from context.
14:44:58.011 [INFO] [com.android.build.gradle.internal.profile.RecordingBuildListener] Task :main:lint in main Finished
14:44:58.012 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :main:lint'
14:44:58.012 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :main:lint' completed
14:44:58.012 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :main:lint (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs.
14:44:58.012 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on :
14:44:58.012 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.11 completed (1 worker(s) in use)
14:44:58.013 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on root.1.11
14:44:58.013 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':',5,main]] finished, busy: 1.213 secs, idle: 0.011 secs
14:44:58.014 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 1.22 secs
14:44:58.014 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 1.219 secs
14:44:58.015 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 5,5,main]] finished, busy: 0.0 secs, idle: 1.219 secs
14:44:58.015 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Execution worker for ':' Thread 4,5,main]] finished, busy: 0.0 secs, idle: 1.218 secs
14:44:58.015 [DEBUG] [org.gradle.execution.plan.DefaultPlanExecutor] Execution worker [Thread[Daemon worker Thread 7,5,main]] finished, busy: 0.0 secs, idle: 1.219 secs
14:44:58.016 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskExecutionGraph] Timing: Executing the DAG took 1.228 secs
14:44:58.018 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
14:44:58.018 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
14:44:58.021 [DEBUG] [org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices] [KOTLIN] Disposed KotlinGradleBuildServices
14:44:58.022 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1 completed (0 worker(s) in use)
14:44:58.022 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 7: released lock on root.1
14:44:58.022 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] A problem was found with the configuration of task ':main:lint'.
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > No value has been specified for property 'lintClassPath'.
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full insights.
14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:44:58.024 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
14:44:58.024 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
14:44:58.024 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 3s
14:44:58.024 [LIFECYCLE] [org.gradle.internal.buildevents.TaskExecutionStatisticsReporter] 2 actionable tasks: 2 executed
14:44:58.024 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run build'
14:44:58.024 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run build' completed
14:44:58.031 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for Build Output Cleanup Cache (/home/pecana/cloni/ics-openvpn/.gradle/buildOutputCleanup)
14:44:58.031 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on Build Output Cleanup Cache (/home/pecana/cloni/ics-openvpn/.gradle/buildOutputCleanup).
14:44:58.032 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for execution history cache (/home/pecana/cloni/ics-openvpn/.gradle/5.6.4/executionHistory)
14:44:58.032 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on execution history cache (/home/pecana/cloni/ics-openvpn/.gradle/5.6.4/executionHistory).
14:44:58.034 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-supplier (/home/pecana/.gradle/caches/5.6.4/md-supplier)
14:44:58.034 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-supplier (/home/pecana/.gradle/caches/5.6.4/md-supplier).
14:44:58.041 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for cache directory md-rule (/home/pecana/.gradle/caches/5.6.4/md-rule)
14:44:58.041 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory md-rule (/home/pecana/.gradle/caches/5.6.4/md-rule).
14:44:58.062 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
14:44:58.063 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 3, disk reads: 1 (avg: 0.003 secs, total: 0.003 secs)
14:44:58.063 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.02 secs
14:44:58.064 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopping 0 deployment handles
14:44:58.064 [DEBUG] [org.gradle.deployment.internal.DefaultDeploymentRegistry] Stopped deployment handles
14:44:58.065 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/home/pecana/cloni/ics-openvpn/.gradle/5.6.4/fileHashes)
14:44:58.065 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/home/pecana/cloni/ics-openvpn/.gradle/5.6.4/fileHashes).
14:44:58.065 [DEBUG] [org.gradle.cache.internal.DefaultPersistentDirectoryStore] VCS Checkout Cache (/home/pecana/cloni/ics-openvpn/.gradle/vcs-1) has last been fully cleaned up 1 hours ago
14:44:58.065 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS Checkout Cache (/home/pecana/cloni/ics-openvpn/.gradle/vcs-1) was closed 0 times.
14:44:58.066 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache VCS metadata (/home/pecana/cloni/ics-openvpn/.gradle/5.6.4/vcsMetadata-1) was closed 0 times.
14:44:58.069 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
14:45:06.172 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientInputForwarder] Dispatching close input message: org.gradle.launcher.daemon.protocol.CloseInput@50e1d8c5
14:45:07.407 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 13: dispatching class org.gradle.launcher.daemon.protocol.CloseInput
14:45:07.410 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Success[value=org.gradle.launcher.exec.BuildActionResult@3f56875e] from daemon DaemonInfo{pid=23718, address=[78726fdc-f4f6-4eee-bd22-a6970b96119b port:41255, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1574862200696, context=DefaultDaemonContext[uid=de4ac2c9-90ef-436c-b141-4b24283a372c,javaHome=/usr/lib/jvm/java-8-openjdk-amd64,daemonRegistryDir=/home/pecana/.gradle/daemon,pid=23718,idleTimeout=10800000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
14:45:07.410 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished
14:45:07.410 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: connection stop
```

**Comment by schwabe** [comment]
```
[org.gradle.internal.buildevents.BuildExceptionReporter] A problem was found with the configuration of task ':main:lint'. 14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > No value has been specified for property 'lintClassPath'. 14:44:58.023 [ERROR]
```

I have no idea where this is coming from...

**Comment by uipko** [comment]
> ```
> [org.gradle.internal.buildevents.BuildExceptionReporter] A problem was found with the configuration of task ':main:lint'. 14:44:58.023 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > No value has been specified for property 'lintClassPath'. 14:44:58.023 [ERROR]
> ```
> 
> I have no idea where this is coming from...

Me neither.
Only thing I can think of is a incorrect Gradle version?  What version are you using, mine is:
```bash
./gradlew --version

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_232 (Oracle Corporation 25.232-b09)
OS:           Linux 5.3.12-arch1-1 amd64
```

**Comment by Pecana** [comment]
> ```shell
> ./gradlew --version
> ```

pecana@local:~/cloni/ics-openvpn$ ./gradlew --version

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_222 (Private Build 25.222-b10)
OS:           Linux 4.15.0-60-generic amd64

It seems the same

**Comment by uipko** [comment]
Indeed, no important differences.

I've no clue why lint is acting up. The gradle tasks `build` and `main:installUiDebug` work fine here.

**Comment by schwabe** [comment]
I think this might have been a bug in some of the dependencies by Google, I seen a similar bug here that went away with the newer gradle versions.
