### ISSUE TITLE
NewGradleSyncNotSupportedException: New Gradle Sync is not supported due to containing Kotlin modules

### ISSUE THREAD

**Issue by yurik94** [schwabe/ics-openvpn#1129]
Just cloned the repo and I can't even sync gradle:

```
com.android.tools.idea.gradle.project.sync.ng.NewGradleSyncNotSupportedException: New Gradle Sync is not supported due to containing Kotlin modules
	at com.android.tools.idea.gradle.project.sync.ng.SyncProjectModels.failIfKotlinPluginAppliedAndKotlinModelIsMissing(SyncProjectModels.java:131)
	at com.android.tools.idea.gradle.project.sync.ng.SyncProjectModels.failIfKotlinPluginAppliedAndKotlinModelIsMissing(SyncProjectModels.java:136)
	at com.android.tools.idea.gradle.project.sync.ng.SyncProjectModels.populate(SyncProjectModels.java:88)
	at com.android.tools.idea.gradle.project.sync.ng.SyncAction.execute(SyncAction.java:59)
	at com.android.tools.idea.gradle.project.sync.ng.SyncAction.execute(SyncAction.java:33)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:80)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner$ActionRunningListener.runAction(ClientProvidedPhasedActionRunner.java:120)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner$ActionRunningListener.run(ClientProvidedPhasedActionRunner.java:110)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner$ActionRunningListener.projectsEvaluated(ClientProvidedPhasedActionRunner.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

```
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

![image](https://user-images.githubusercontent.com/13189646/72663639-29d7ca00-39f5-11ea-842e-748738a3e142.png)

**Comment by schwabe** [comment]
If have no idea but Google leads to this:
https://stackoverflow.com/questions/56607089/new-gradle-sync-is-not-supported-due-to-containing-kotlin-modules-using-an-unsup

**Comment by yurik94** [comment]
![image](https://user-images.githubusercontent.com/13189646/72663931-3a3d7400-39f8-11ea-95f9-8902813e66c4.png)

Already upgraded from 1.6 to 1.8

Reopened project, but still stuck 😢

**Comment by schwabe** [comment]
did you try ./gradlew build from command line?

**Comment by yurik94** [comment]
> did you try ./gradlew build from command line?

Thanks.
I managed to build & install by command line but I still can't get to sync and use IDE features, it's the first time it happens and that I have to use gradle.kts format too.
If anyone has any sort of advice I'll try it.

**Comment by yurik94** [comment]
Just for recap, when I click sync with Gradle this is the output:
```
2020-01-21
11:05	Gradle sync started with IDEA sync

11:05	Gradle sync finished in 17 ms (from cached state)

11:05	NDK Resolution Outcome: Project settings: Gradle model version=5.6.4, NDK version is UNKNOWN
```
Of course I have NDK configured (and working in other projects!) in local.properties:
```
ndk.dir=/Users/kevin/Library/Android/sdk/ndk/20.1.5948944
sdk.dir=/Users/kevin/Library/Android/sdk
```

**Comment by yurik94** [comment]
I tried to reimport project using "Import from Gradle..." and it finally worked!
Seems to sync properly even though I had this warning:
![image](https://user-images.githubusercontent.com/13189646/72798849-3ef66800-3c44-11ea-89d5-741de2746a29.png)

**Comment by schwabe** [comment]
Yeah. That warning is always there.

**Comment by ataravati** [comment]
@yurik94 I'm having the same issue. How did you import the project using "Import from Gradle..."? When I try that, it says the project already exists.

**Comment by yurik94** [comment]
> @yurik94 I'm having the same issue. How did you import the project using "Import from Gradle..."? When I try that, it says the project already exists.

Mmm... Try cloning again, or delete .gradle dir inside project

**Comment by ataravati** [comment]
> > @yurik94 I'm having the same issue. How did you import the project using "Import from Gradle..."? When I try that, it says the project already exists.
> 
> Mmm... Try cloning again, or delete .gradle dir inside project

I managed to do that by deleting the `.gradle` and `.idea` directories and then clicking on `build.gradle` and choosing Android Studio to open it.
