### ISSUE TITLE
App crashes when clicking edit icon on a managed configuration vpn

### ISSUE THREAD

**Issue by Uldiniad** [schwabe/ics-openvpn#1131]
Android Version: 9
Android ROM: AOSP
Device: sargo
App Version: Installed from Play Store

```
01-21 15:36:49.953 24964 24964 E AndroidRuntime: FATAL EXCEPTION: main
01-21 15:36:49.953 24964 24964 E AndroidRuntime: Process: de.blinkt.openvpn, PID: 24964
01-21 15:36:49.953 24964 24964 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
01-21 15:36:49.953 24964 24964 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.KeyChainSettingsFragment.initKeychainViews(KeyChainSettingsFragment.java:141)
01-21 15:36:49.953 24964 24964 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.Settings_UserEditable.onCreateView(Settings_UserEditable.java:29)
```

**Comment by schwabe** [comment]
Should be fixed in newest version
