### ISSUE TITLE
App crashes immediately when clicking "TLS auth file"

### ISSUE THREAD

**Issue by lulol** [schwabe/ics-openvpn#1155]
Tested with two different phones running Android 6.0 and 7.0

 OpenVPN for Android 0.7.14 installed from Google Play store.

- Create new profile, enter any name.
- Enable "Use TLS auth"
- Click "TLS auth file"
- App crashes.

Same issue for an existing profile already with its tls file configured with a previous app version when clicking "TLS auth file".

Can't find any relevant log entry being generated after the crash even setting the detail log level to max.

**Comment by SFMason-USF** [comment]
Getting the same thing on Android 10, Google Pixel 3. Here is what looks like the exception that causes the crash from logcat:

```
03-03 13:28:14.159 16649 16649 E RecyclerView: No adapter attached; skipping layout
03-03 13:28:16.876 16649 16649 D AndroidRuntime: Shutting down VM
03-03 13:28:16.879 16649 16649 E AndroidRuntime: FATAL EXCEPTION: main
03-03 13:28:16.879 16649 16649 E AndroidRuntime: Process: de.blinkt.openvpn, PID: 16649
03-03 13:28:16.879 16649 16649 E AndroidRuntime: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:794)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at de.blinkt.openvpn.fragments.Settings_Authentication.startFileDialog(Settings_Authentication.java:198)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at de.blinkt.openvpn.fragments.Settings_Authentication.onPreferenceClick(Settings_Authentication.java:211)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.preference.Preference.performClick(Preference.java:1184)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.preference.Preference.performClick(Preference.java:1166)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at androidx.preference.Preference$1.onClick(Preference.java:181)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.view.View.performClick(View.java:7259)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7236)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.view.View.access$3600(View.java:801)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:27892)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-03 13:28:16.879 16649 16649 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
