### ISSUE TITLE
Null object refence error.

### ISSUE THREAD

**Issue by abhishekdeshkar** [schwabe/ics-openvpn#1281]
````
 --------- beginning of crash
2020-12-20 20:37:16.850 28712-28712/de.blinkt.openvpn.remote E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blinkt.openvpn.remote, PID: 28712
    java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
        at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:277)
        at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:265)
        at android.view.View.performClick(View.java:7261)
        at android.view.View.performClickInternal(View.java:7223)
        at android.view.View.access$3800(View.java:824)
        at android.view.View$PerformClick.run(View.java:27721)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
```

I'm debugging on my phone and app keep crashing when I click on "Add Profile" it crashed. 

It crashes for everything.

Android Version : 10

**Comment by schwabe** [comment]
I need more context then that to figure out what happening. The stacktrace does not look like "Add profile" that is confusing.
