### ISSUE TITLE
VPN remains in unusable state after app is killed

### ISSUE THREAD

**Issue by syphyr** [schwabe/ics-openvpn#1354]
# General information
1. Android version: lineage-14.1 (nougat)
2. Android Vendor/Custom ROM: lineage
3. Device: T813
4. Version of the app (version number/play store version/self-built): latest code on master branch
 
# Description of the issue

Android (nougat) often kills background applications when memory is low. When openvpn is killed by the system under memory constraints, the vpn connection is not actually killed completely (the key icon remains in the notification bar). This puts tun0 in a weird state that prevents the vpn connection from working again until the device is restarted. It looks like when openvpn gets killed by the system, tun0 remains and gets into a unusable state (ever after restarting openvpn and connecting again to vpn server). 

Suggested solution: Add a root option that let's openvpn create a transparent proxy to bypass android's unreliable VPN. This solution would also create a reliable failsafe in case server connection drops.

**Comment by syphyr** [comment]
After Android has killed the openvpn process due to low resources and left tun0 is a halfway state, I tried deleting the VPN connection from Android's VPN settings and restarted Openvpn.  This causes a crash and demonstrates the state that openvpn causes tun0 to be in:

```
--------- beginning of crash
08-16 01:14:04.445 11815 11815 E AndroidRuntime: FATAL EXCEPTION: main
08-16 01:14:04.445 11815 11815 E AndroidRuntime: Process: de.blinkt.openvpn, PID: 11815
08-16 01:14:04.445 11815 11815 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3454)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getStringExtra(java.lang.String)' on a null object reference
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.VPNProfileList.showUserRequestDialogIfNeeded(VPNProfileList.java:98)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.VPNProfileList.lambda$updateState$0$VPNProfileList(VPNProfileList.java:92)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.-$$Lambda$VPNProfileList$Miy3Ym5WuPbwHKXh9LepmApm9pc.run(lambda)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.Activity.runOnUiThread(Activity.java:5871)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.VPNProfileList.updateState(VPNProfileList.java:88)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at de.blinkt.openvpn.core.VpnStatus.addStateListener(VpnStatus.java:274)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at de.blinkt.openvpn.fragments.VPNProfileList.onResume(VPNProfileList.java:248)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3126)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3084)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:458)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:447)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:195)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6812)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
08-16 01:14:04.445 11815 11815 E AndroidRuntime: 	... 8 more
08-16 01:14:04.445   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:04.452   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:04.469   916  2494 W ActivityManager:   Force finishing activity de.blinkt.openvpn/.activities.MainActivity
08-16 01:14:04.487   916   943 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{9859f86 1996:com.teslacoilsw.notifier/u0a163} (pid=1996, uid=10163) requires android.permission.READ_LOGS due to sender android (uid 1000)
08-16 01:14:04.565   916 12194 I OpenGLRenderer: Initialized EGL, version 1.4
08-16 01:14:04.566   916 12194 D OpenGLRenderer: Swap behavior 1
08-16 01:14:04.636 11833 12201 I OpenVPN : Starting openvpn
08-16 01:14:04.975   916   943 W ActivityManager: Activity pause timeout for ActivityRecord{b47b1d5 u0 de.blinkt.openvpn/.activities.MainActivity t49727 f}
08-16 01:14:05.750   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:05.770   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:05.785   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:05.792   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:06.961   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:06.969   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:07.526   384   384 I MSM-irqbalance: Decided to move IRQ224 from CPU3 to CPU0
08-16 01:14:08.337   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:08.347   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:08.428   916  2490 D Vpn     : setting state=CONNECTING, reason=establish
08-16 01:14:08.429   916  2490 D VpnJni  : Address added on tun0: 10.20.0.29/16
08-16 01:14:08.436   916  2490 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{ ni{[type: VPN[], state: CONNECTING/CONNECTING, reason: (unspecified), extra: (none), failover: false, available: false, roaming: false, metered: false]}  network{106}  nethandle{455282969310}  lp{{InterfaceName: tun0 LinkAddresses: [10.20.0.29/16,]  Routes: [0.0.0.0/1 -> 0.0.0.0 tun0,128.0.0.0/2 -> 0.0.0.0 tun0,192.0.0.0/9 -> 0.0.0.0 tun0,192.128.0.0/11 -> 0.0.0.0 tun0,192.160.0.0/13 -> 0.0.0.0 tun0,192.168.0.0/24 -> 0.0.0.0 tun0,192.168.2.0/23 -> 0.0.0.0 tun0,192.168.4.0/22 -> 0.0.0.0 tun0,192.168.8.0/21 -> 0.0.0.0 tun0,192.168.16.0/20 -> 0.0.0.0 tun0,192.168.32.0/19 -> 0.0.0.0 tun0,192.168.64.0/18 -> 0.0.0.0 tun0,192.168.128.0/17 -> 0.0.0.0 tun0,192.169.0.0/16 -> 0.0.0.0 tun0,192.170.0.0/15 -> 0.0.0.0 tun0,192.172.0.0/14 -> 0.0.0.0 tun0,192.176.0.0/12 -> 0.0.0.0 tun0,192.192.0.0/10 -> 0.0.0.0 tun0,193.0.0.0/8 -> 0.0.0.0 tun0,194.0.0.0/7 -> 0.0.0.0 tun0,196.0.0.0/6 -> 0.0.0.0 tun0,200.0.0.0/5 -> 0.0.0.0 tun0,208.0.0.0/4 -> 0.0.0.0 tun0,::/0 unreachable,] DnsAddresses: [10.20.0.1,] Domains:  MTU: 0}}  nc{[ Transports: VPN Capabilities: NOT_RESTRICTED&TRUSTED]}  Score{0}  everValidated{false}  lastValidated{false}  created{false} lingering{false} explicitlySelected{false} acceptUnvalidated{false} everCaptivePortalDetected{false} lastCaptivePortalDetected{false} }
08-16 01:14:08.437   916  2490 D Vpn     : setting state=CONNECTED, reason=agentConnect
08-16 01:14:08.437   916  1012 D ConnectivityService: NetworkAgentInfo [VPN () - 106] EVENT_NETWORK_INFO_CHANGED, going from null to CONNECTING
08-16 01:14:08.437   916  2490 I Vpn     : Established by de.blinkt.openvpn on tun0
08-16 01:14:08.441   414   938 I Netd    : Destroyed 4 sockets for UidRanges{ 0-99999 } skip={1016 10200} in 1.6 ms
08-16 01:14:08.441  7153 12163 V NativeCrypto: Read error: ssl=0x7f76a1c6c8: I/O error during system call, Software caused connection abort
08-16 01:14:08.441  7153 12163 V NativeCrypto: Write error: ssl=0x7f76a1c6c8: I/O error during system call, Broken pipe
08-16 01:14:08.442  7153 12163 V NativeCrypto: Write error: ssl=0x7f76a1c6c8: I/O error during system call, Broken pipe
08-16 01:14:08.442  7153 12163 V NativeCrypto: SSL shutdown failed: ssl=0x7f76a1c6c8: I/O error during system call, Success
08-16 01:14:08.442   916  1012 D ConnectivityService: NetworkAgentInfo [VPN () - 106] EVENT_NETWORK_INFO_CHANGED, going from CONNECTING to CONNECTED
08-16 01:14:08.442   916  1012 D ConnectivityService: Adding iface tun0 to network 106
08-16 01:14:08.443   414   938 E Netd    : interface tun0 already assigned to netId 101
08-16 01:14:08.443  1444 12000 V NativeCrypto: Read error: ssl=0x7f4b3d9908: I/O error during system call, Software caused connection abort
08-16 01:14:08.443  4574  4703 D Orbot   : orConnStatus (RaulandRelay): CLOSED
08-16 01:14:08.444   916  1012 E ConnectivityService: Exception adding interface: java.lang.IllegalStateException: command '330 network interface add 106 tun0' failed with '400 330 addInterfaceToNetwork() failed (Device or resource busy)'
08-16 01:14:08.444   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.445   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '331 network route add 106 tun0 0.0.0.0/1' failed with '400 331 addRoute() failed (No such file or directory)'
08-16 01:14:08.446   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.447   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '332 network route add 106 tun0 128.0.0.0/2' failed with '400 332 addRoute() failed (No such file or directory)'
08-16 01:14:08.448   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.448  1444 12000 V NativeCrypto: SSL shutdown failed: ssl=0x7f4b3d9908: I/O error during system call, Broken pipe
08-16 01:14:08.449  1444 12000 E WakeLock: GCM_HB_ALARM release without a matched acquire!
08-16 01:14:08.449  1444 12000 W WakeLock: GCM_HB_ALARM counter does not exist
08-16 01:14:08.450   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '333 network route add 106 tun0 192.0.0.0/9' failed with '400 333 addRoute() failed (No such file or directory)'
08-16 01:14:08.451   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.452   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '334 network route add 106 tun0 192.128.0.0/11' failed with '400 334 addRoute() failed (No such file or directory)'
08-16 01:14:08.453  1444 12000 E WakeLock: GCM_CONN_ALARM release without a matched acquire!
08-16 01:14:08.453   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.453  1444 12000 W WakeLock: GCM_CONN_ALARM counter does not exist
08-16 01:14:08.455   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '335 network route add 106 tun0 192.160.0.0/13' failed with '400 335 addRoute() failed (No such file or directory)'
08-16 01:14:08.455   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.456   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '336 network route add 106 tun0 192.168.0.0/24' failed with '400 336 addRoute() failed (No such file or directory)'
08-16 01:14:08.457   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.457   916   916 D ZenLog  : intercepted: 0|de.blinkt.openvpn|1346787898|null|10200,alarmsOnly
08-16 01:14:08.458   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:08.459   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '337 network route add 106 tun0 192.168.2.0/23' failed with '400 337 addRoute() failed (No such file or directory)'
08-16 01:14:08.460   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.461   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '338 network route add 106 tun0 192.168.4.0/22' failed with '400 338 addRoute() failed (No such file or directory)'
08-16 01:14:08.462   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.463   916   916 V NotificationService: pkg=de.blinkt.openvpn canInterrupt=false intercept=true
08-16 01:14:08.464   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '339 network route add 106 tun0 192.168.8.0/21' failed with '400 339 addRoute() failed (No such file or directory)'
08-16 01:14:08.465   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.471   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '340 network route add 106 tun0 192.168.16.0/20' failed with '400 340 addRoute() failed (No such file or directory)'
08-16 01:14:08.471   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.473   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '341 network route add 106 tun0 192.168.32.0/19' failed with '400 341 addRoute() failed (No such file or directory)'
08-16 01:14:08.474   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.475   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '342 network route add 106 tun0 192.168.64.0/18' failed with '400 342 addRoute() failed (No such file or directory)'
08-16 01:14:08.475   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.476   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '343 network route add 106 tun0 192.168.128.0/17' failed with '400 343 addRoute() failed (No such file or directory)'
08-16 01:14:08.477   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.478   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '344 network route add 106 tun0 192.169.0.0/16' failed with '400 344 addRoute() failed (No such file or directory)'
08-16 01:14:08.478   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.480   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '345 network route add 106 tun0 192.170.0.0/15' failed with '400 345 addRoute() failed (No such file or directory)'
08-16 01:14:08.481   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.483   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '346 network route add 106 tun0 192.172.0.0/14' failed with '400 346 addRoute() failed (No such file or directory)'
08-16 01:14:08.483   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.485   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '347 network route add 106 tun0 192.176.0.0/12' failed with '400 347 addRoute() failed (No such file or directory)'
08-16 01:14:08.486   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.490   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '348 network route add 106 tun0 192.192.0.0/10' failed with '400 348 addRoute() failed (No such file or directory)'
08-16 01:14:08.491   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.493   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '349 network route add 106 tun0 193.0.0.0/8' failed with '400 349 addRoute() failed (No such file or directory)'
08-16 01:14:08.493   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.494   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '350 network route add 106 tun0 194.0.0.0/7' failed with '400 350 addRoute() failed (No such file or directory)'
08-16 01:14:08.495   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.496   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '351 network route add 106 tun0 196.0.0.0/6' failed with '400 351 addRoute() failed (No such file or directory)'
08-16 01:14:08.497   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.498   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '352 network route add 106 tun0 200.0.0.0/5' failed with '400 352 addRoute() failed (No such file or directory)'
08-16 01:14:08.499   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.500   916  1012 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '353 network route add 106 tun0 208.0.0.0/4' failed with '400 353 addRoute() failed (No such file or directory)'
08-16 01:14:08.501   414   938 E Netd    : interface tun0 assigned to netId 101, not 106
08-16 01:14:08.623   916  2494 W ActivityManager:   Force finishing activity de.blinkt.openvpn/.LaunchVPN
08-16 01:14:08.627   916  2494 W ActivityManager:   Force finishing activity de.blinkt.openvpn/.activities.MainActivity
08-16 01:14:08.631   916  2494 I ActivityManager: Killing 11815:de.blinkt.openvpn/u0a200 (adj 900): crash
```

**Comment by schwabe** [comment]
To be honest, LineageOS/Cyanogenmod has a colourful history of messing with the network stack and breaking VPN.  So it wouldn't surprise if that is another problem specific to LinageOS. I never seen that behaviour you describing from any other device (apart from 4.4.1 hickup)

As for the root option. I don't have any rooted devices anymore apart from an old  Sony Lt26W with Android 4.1. So I don't have any hardware to develop that on.

**Comment by syphyr** [comment]
It turns out that openvpn was not actually being killed by memory constraints in my situation. When I added "ping-restart 300" to custom options, it would make openvpn randomly crash, leaving it in that weird state with network interface. After removing "ping-restart 300", openvpn has not had any issues for 3 days so far.

**Comment by syphyr** [comment]
I'm going to close this issue since I think it was just a configuration problem on my end.  Since removing "ping-restart 300" from custom options, I have not had any issues with openvpn.
