### ISSUE TITLE
import-profile support causing NPE when selecting OpenVPN from Notifications

### ISSUE THREAD

**Issue by syphyr** [schwabe/ics-openvpn#1360]
# General information
1. Android Version: Nougat 7.1
2. Android Vendor/Custom ROM: Lineage 14.1
3. Device: T813
4. Version of the app (version number/play store version/self-built): self-built on latest Master branch
 
# Description of the issue

The commit 09c5cb0a0d33c58897026b7b4b1901c1ddc088f1 is causing a null pointer exception when selecting openvpn from the notification bar menu.  Every time I select openvpn from notification bar, it crashes with NPE. 

```
09-06 00:36:20.154 15364 15364 E AndroidRuntime: FATAL EXCEPTION: main
09-06 00:36:20.154 15364 15364 E AndroidRuntime: Process: de.blinkt.openvpn, PID: 15364
09-06 00:36:20.154 15364 15364 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3454)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at de.blinkt.openvpn.activities.MainActivity.onResume(MainActivity.java:82)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6788)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
09-06 00:36:20.154 15364 15364 E AndroidRuntime: 	... 10 more
```

**Comment by syphyr** [comment]
This issue is fixed by the following PR: https://github.com/schwabe/ics-openvpn/pull/1361
