### ISSUE TITLE
Getting X509 Name from certificate: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]

### ISSUE THREAD

**Issue by dmitrygribenchuk** [schwabe/ics-openvpn#1432]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 11 (RP1A.200720.011)
2. MIUI 12.5.5
3. Redmi Redmi Note 8 Pro (begonia)
4. official build 0.7.30

Hello. have I choose "check peer certificate fingerprint" and leave it blank I have a stack trace on connection:

2022-01-02 21:57:57 Getting X509 Name from certificate: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
java.lang.NoSuchMethodException: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
 at java.lang.Class.getMethod(Class.java:2072)
 at java.lang.Class.getMethod(Class.java:1693)
 at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:136)
 at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:82)
 at de.blinkt.openvpn.views.FileSelectLayout.setData(FileSelectLayout.java:155)
 at de.blinkt.openvpn.fragments.Settings_Basic.loadPreferences(Settings_Basic.java:192)
 at de.blinkt.openvpn.fragments.KeyChainSettingsFragment.onStart(KeyChainSettingsFragment.kt:208)
 at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
 at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
 at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
 at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
 at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
 at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
 at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
 at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:767)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3633)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2411)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2677)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8622)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
 at android.view.Choreographer.doCallbacks(Choreographer.java:799)
 at android.view.Choreographer.doFrame(Choreographer.java:734)
 at android.view.Choreog
rapher$FrameDisplayEventReceiver.run(Choreographer.java:960)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8057)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

2022-01-02 21:57:58 Getting X509 Name from certificate: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]

java.lang.NoSuchMethodException: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
 at java.lang.Class.getMethod(Class.java:2072)
 at java.lang.Class.getMethod(Class.java:1693)
 at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:136)
 at de.blinkt.openvpn.fragments.KeyChainSettingsFragment$setCertificate$1.run(KeyChainSettingsFragment.kt:131)

**Comment by dmitrygribenchuk** [comment]
Duplicate by #1265

**Comment by gokaybiz** [comment]
I have same issue also.
