### ISSUE TITLE
Edit configuration stack trace

### ISSUE THREAD

**Issue by dmitrygribenchuk** [schwabe/ics-openvpn#1499]
# General information
1. Android 11
2. MIUI 12.5.7 (latest)
3. Redmi Note 8 Pro
4. OpenVPN for Android 0.7.37 (latest)
5. User auth via client certificate (x509)
# Description of the issue

Hello. Found a stack trace when:
1) Connect to VPN server
2) Choose edit configuration via menu
3) Do do nothing in confuration and return to connection log

`2022-06-10 12:20:01 Getting X509 Name from certificate: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
java.lang.NoSuchMethodException: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
 at java.lang.Class.getMethod(Class.java:2072)
 at java.lang.Class.getMethod(Class.java:1693)
 at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:136)
 at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:82)
 at de.blinkt.openvpn.views.FileSelectLayout.setData(FileSelectLayout.java:155)
 at de.blinkt.openvpn.fragments.Settings_Basic.loadPreferences(Settings_Basic.java:192)
 at de.blinkt.openvpn.fragments.KeyChainSettingsFragment.onStart(KeyChainSettingsFragment.kt:208)
 at androidx.fragment.app.Fragment.performStart(Fragment.java:3053)
 at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:587)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
 at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
 at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
 at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
 at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
 at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
 at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:767)
 at android.view.View.measure(View.java:26057)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3635)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2413)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2679)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2135)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8624)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
 at android.view.Choreographer.doCallbacks(Choreographer.java:799)
 at android.view.Choreographer.doFrame(Choreographer.java:734)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:960)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8057)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
2022-06-10 12:20:01 Getting X509 Name from certificate: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
java.lang.NoSuchMethodException: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
 at java.lang.Class.getMethod(Class.java:2072)
 at java.lang.Class.getMethod(Class.java:1693)
 at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:136)
 at de.blinkt.openvpn.fragments.KeyChainSettingsFragment$setCertificate$1.run(KeyChainSettingsFragment.kt:131)`

[openvpn.trace.zip](https://github.com/schwabe/ics-openvpn/files/8877807/openvpn.trace.zip)

**Comment by dmitrygribenchuk** [comment]
Looks like #1265

**Comment by dmitrygribenchuk** [comment]
Also can reproduce at 0.7.41

**Comment by dmitrygribenchuk** [comment]
Seems as fixed at 0.7.42
