### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by AhmadNosratian** [schwabe/ics-openvpn#1552]
I tried to run this project on my device but it caused this error.
xiaomi Note10 pro
Andorid 12

```
E/.openvpn.remot: open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blinkt.openvpn.remote, PID: 10480
    java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
        at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:297)
        at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:285)
```

**Comment by AhmadNosratian** [comment]
```
10/28 11:18:14: Launching 'remoteExample' on Xiaomi M2101K6R.
Install successfully finished in 947 ms.
$ adb shell am start -n "de.blinkt.openvpn.remote/de.blinkt.openvpn.remote.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 10480 on device 'xiaomi-m2101k6r-4669bf86'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/AppScoutStateMachine: 10480-ScoutStateMachinecreated
W/re-initialized>: type=1400 audit(0.0:188377): avc: granted { execute } for path="/data/data/de.blinkt.openvpn.remote/code_cache/startup_agents/4cead168-agent.so" dev="dm-10" ino=289434 scontext=u:r:untrusted_app:s0:c139,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c139,c257,c512,c768 tclass=file app=de.blinkt.openvpn.remote
V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-962d6e1a.jar
W/.openvpn.remot: DexFile /data/data/de.blinkt.openvpn.remote/code_cache/.studio/instruments-962d6e1a.jar is in boot class path but is not in a known location
V/studio.deploy: ModifyParameterTransform failed: Landroid/app/ApplicationLoaders;
W/.openvpn.remot: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/.openvpn.remot: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/.openvpn.remot: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/.openvpn.remot: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
W/.openvpn.remot: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/.openvpn.remot: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
W/.openvpn.remot: Current dex file has more than one class in it. Calling RetransformClasses on this class might fail if no transformations are applied to it!
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10395; state: DISABLED
I/Perf: Connecting to perf service.
V/GraphicsEnvironment: ANGLE Developer option for 'de.blinkt.openvpn.remote' set to: 'default'
V/GraphicsEnvironment: Updatable production driver is not supported on the device.
I/ForceDarkHelperStubImpl: initialize for de.blinkt.openvpn.remote , ForceDarkOrigin
D/OpenGLRenderer: JNI_OnLoad success
I/MiuiForceDarkConfig: setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/ViewScrollStubImpl: the value of ScrollFrictionRes is: 0.019499999
D/IS_CTS_MODE: false
D/MULTI_WINDOW_SWITCH_ENABLED: false
D/IS_CTS_MODE: false
D/MULTI_WINDOW_SWITCH_ENABLED: false
D/IS_CTS_MODE: false
D/MULTI_WINDOW_SWITCH_ENABLED: false
D/DecorView[]: getWindowModeFromSystem  windowmode is 1
I/AdrenoGLES-0: QUALCOMM build                   : c5f0e23, I9972db7aac
    Build Date                       : 04/28/21
    OpenGL ES Shader Compiler Version: EV031.32.02.10
    Local Branch                     : mybrancheba83f1e-3815-f156-b760-08f1eafda2d8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
I/AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
D/hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
E/.openvpn.remot: open libmigui.so failed! dlopen - dlopen failed: library "libmigui.so" not found
I/OpenGLRenderer: Davey! duration=9222904236101ms; Flags=1, FrameTimelineVsyncId=19952005, IntendedVsync=467800753240129, Vsync=467800753240129, InputEventId=0, HandleInputStart=467800754328307, AnimationStart=467800754333828, PerformTraversalsStart=467800754335807, DrawStart=467800784841484, FrameDeadline=467800769906795, FrameInterval=467800754170390, FrameStartTime=16666666, SyncQueued=467800790709140, SyncStart=467800790788776, IssueDrawCommandsStart=467800791126744, SwapBuffers=467800798863880, FrameCompleted=9223372036854775807, DequeueBufferDuration=11562, QueueBufferDuration=1216094, GpuCompleted=9223372036854775807, SwapBuffersCompleted=467800800979036, DisplayPresentTime=0, 
D/DecorView[]: onWindowFocusChanged hasWindowFocus true
D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2251)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:404)
        at libcore.io.ForwardingOs.socket(ForwardingOs.java:821)
        at libcore.io.IoBridge.socket(IoBridge.java:840)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:514)
        at java.net.Socket.getImpl(Socket.java:577)
        at java.net.Socket.setSoTimeout(Socket.java:1203)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at de.blinkt.openvpn.remote.MainFragment.getMyOwnIP(MainFragment.java:343)
        at de.blinkt.openvpn.remote.MainFragment$3.run(MainFragment.java:260)
I/OpenGLRenderer: Davey! duration=9222904229099ms; Flags=0, FrameTimelineVsyncId=-1, IntendedVsync=467807754781013, Vsync=467807754796794, InputEventId=10562124, HandleInputStart=467807754889346, AnimationStart=467807754898773, PerformTraversalsStart=467807754902211, DrawStart=467807755468825, FrameDeadline=9223372036854775807, FrameInterval=467807754796794, FrameStartTime=16666666, SyncQueued=467807757341638, SyncStart=467807757444606, IssueDrawCommandsStart=467807757797419, SwapBuffers=467807761503409, FrameCompleted=9223372036854775807, DequeueBufferDuration=81458, QueueBufferDuration=1812500, GpuCompleted=9223372036854775807, SwapBuffersCompleted=467807764393096, DisplayPresentTime=0, 
I/OpenGLRenderer: Davey! duration=9222904229001ms; Flags=0, FrameTimelineVsyncId=19952566, IntendedVsync=467807853375830, Vsync=467807853375830, InputEventId=1039990555, HandleInputStart=467807854032523, AnimationStart=467807854040544, PerformTraversalsStart=467807854044086, DrawStart=467807854629815, FrameDeadline=467807886709162, FrameInterval=467807853955648, FrameStartTime=16666666, SyncQueued=467807856408773, SyncStart=467807856594033, IssueDrawCommandsStart=467807857037419, SwapBuffers=467807860476065, FrameCompleted=9223372036854775807, DequeueBufferDuration=50364, QueueBufferDuration=1416250, GpuCompleted=9223372036854775807, SwapBuffersCompleted=467807863112158, DisplayPresentTime=0, 
I/OpenGLRenderer: Davey! duration=9222904227801ms; Flags=0, FrameTimelineVsyncId=19952644, IntendedVsync=467809053413182, Vsync=467809053413182, InputEventId=759270427, HandleInputStart=467809054742523, AnimationStart=467809054751168, PerformTraversalsStart=467809054755648, DrawStart=467809055390752, FrameDeadline=467809070079848, FrameInterval=467809054652523, FrameStartTime=16666666, SyncQueued=467809057368460, SyncStart=467809057571741, IssueDrawCommandsStart=467809058333929, SwapBuffers=467809061837783, FrameCompleted=9223372036854775807, DequeueBufferDuration=77448, QueueBufferDuration=1548438, GpuCompleted=9223372036854775807, SwapBuffersCompleted=467809064419814, DisplayPresentTime=0, 
I/OpenGLRenderer: Davey! duration=9222904226246ms; Flags=0, FrameTimelineVsyncId=-1, IntendedVsync=467810608451897, Vsync=467810608468928, InputEventId=758555322, HandleInputStart=467810608594085, AnimationStart=467810608607001, PerformTraversalsStart=467810608610803, DrawStart=467810609334397, FrameDeadline=9223372036854775807, FrameInterval=467810608468928, FrameStartTime=16666666, SyncQueued=467810611589762, SyncStart=467810611722991, IssueDrawCommandsStart=467810612032366, SwapBuffers=467810615423251, FrameCompleted=9223372036854775807, DequeueBufferDuration=61667, QueueBufferDuration=1457604, GpuCompleted=9223372036854775807, SwapBuffersCompleted=467810617996793, DisplayPresentTime=0, 
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blinkt.openvpn.remote, PID: 10480
    java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
        at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:297)
        at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:285)
        at android.view.View.performClick(View.java:7750)
        at android.view.View.performClickInternal(View.java:7727)
        at android.view.View.access$3700(View.java:858)
        at android.view.View$PerformClick.run(View.java:29115)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8168)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
D/OOMEventManagerFK: checkEventAndDumpForJE: 0
```

**Comment by schwabe** [comment]
You need OpenVPN for android installed to run the remote example. The remote example is just an example and does not catch all error conditions.
