### ISSUE TITLE
Android 9 problem

### ISSUE THREAD

**Issue by mesterj** [schwabe/ics-openvpn#1558]
# General information
1. Android Version
Android 9.0 
3. Android Vendor/Custom ROM
Lenovo
4. Device
Lenovo TB-X605L
5. Version of the app (version number/play store version/self-built)
 0.7.42
# Description of the issue
When I try to connect my profile I got an ANR message
# Log (if applicable)
2022-11-22 11:41:29.666 19289-21483 AndroidRuntime          pid-19289                            E  FATAL EXCEPTION: OpenVPNManagementThread
                                                                                                    Process: de.blinkt.openvpn:openvpn, PID: 19289
                                                                                                    java.lang.NoSuchMethodError: No direct method <init>(Ljava/net/InetAddress;I)V in class Landroid/net/IpPrefix; or its super classes (declaration of 'android.net.IpPrefix' appears in /system/framework/framework.jar)
                                                                                                    	at de.blinkt.openvpn.core.NetworkSpace$IpAddress.getPrefix(NetworkSpace.java:222)
                                                                                                    	at de.blinkt.openvpn.core.NetworkUtils.getLocalNetworks(NetworkUtils.java:60)
                                                                                                    	at de.blinkt.openvpn.core.OpenVPNService.addLocalNetworksToRoutes(OpenVPNService.java:997)
                                                                                                    	at de.blinkt.openvpn.core.OpenVPNService.openTun(OpenVPNService.java:769)
                                                                                                    	at de.blinkt.openvpn.core.OpenVpnManagementThread.sendTunFD(OpenVpnManagementThread.java:628)
                                                                                                    	at de.blinkt.openvpn.core.OpenVpnManagementThread.processNeedCommand(OpenVpnManagementThread.java:597)
                                                                                                    	at de.blinkt.openvpn.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:295)
                                                                                                    	at de.blinkt.openvpn.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:266)
                                                                                                    	at de.blinkt.openvpn.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:219)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
2022-11-22 11:41:29.756  1387-1440  ActivityManager         pid-1387                             I  Showing crash dialog for package de.blinkt.openvpn u0

```
log contents
```

# Configuration file
I think it is not important because it is working on Android 10 
```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by rbrouwer** [comment]
With OpenVPN 3 Core enabled:

tun error: no direct method <init>(ljava/net/inetaddress;i)v in class landroid/net/ipprefix; or its super classes (declaration of 'android.net.ipprefix' appears in /system/framework/framework.jar!classes2.dex)

will end the OpenVPN Thread, but the application will not crash (it also will not connect)

**Comment by mesterj** [comment]
I have got ANR message. And as you see , a crash . Which Android version did you trie?

**Comment by rbrouwer** [comment]
Also Android 9, but I had OpenVPN 3 Core enabled under the application's settings. If I disable it, the application also crashes for me.

Device for me: Galaxy S8
