### ISSUE TITLE
PID-ERR no root!

### ISSUE THREAD

**Issue by LiviusMaximus** [schwabe/ics-openvpn#1600]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 11.1
2. Android Vendor/Custom ROM VollaOS
3. Device  F-Droid built and signed version 0.7.43 running on volla Volla Phone 22 (pri_board), Android 11 (RQ3A.211001.001) API 30, ABI arm64-v8a, (Gigaset/GS290_EEA/GS290:10/QP1A.190711.020/1597810494:user/release-keys)
4. Version of the app (version number/play store version/self-built)
 0.7.43
# Description of the issue
# Log (if applicable)
14:16 PID_ERR replay-window backtrack occurred [1] [SSL-0] [0_0000000000000000000000000000000000000EEEEEEEEEEEEEEEEEEEEEEEEE] 0:106 0:105 t=1679832989[0] r=[0,64,15,1,1] sl=[22,64,64,528]

```
log contents
14:42 Getting X509 Name from certificate: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]

java.lang.NoSuchMethodException: com.android.org.bouncycastle.asn1.x509.X509Name.getInstance [class java.lang.Object]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:136)
	at de.blinkt.openvpn.core.X509Utils.getCertificateFriendlyName(X509Utils.java:82)
	at de.blinkt.openvpn.views.FileSelectLayout.setData(FileSelectLayout.java:155)
	at de.blinkt.openvpn.fragments.Settings_Basic.loadPreferences(Settings_Basic.java:192)
	at de.blinkt.openvpn.fragments.KeyChainSettingsFragment.onStart(KeyChainSettingsFragment.kt:208)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3162)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:496)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
	at android.view.View.measure(View.java:25466)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3402)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2246)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
```
# Configuration file
# Config for OpenVPN 2.x
# Enables connection to GUI
management /data/user/0/de.blinkt.openvpn/cache/mgmtsocket unix
management-client
management-query-passwords
management-hold

setenv IV_GUI_VER "de.blinkt.openvpn 0.7.43" 
setenv IV_SSO openurl,webauth,crtext
setenv IV_PLAT_VER "30 11 arm64-v8a volla pri_board Volla Phone 22"
setenv IV_HWADDR 38:30:35:36:62:39:63
tls-cert-profile preferred
machine-readable-output
allow-recursive-routing
ifconfig-nowarn
client
verb 4
connect-retry-max 50
connect-retry 5 300
resolv-retry 60
dev tun
remote 91.132.139.75 1194 udp
 connect-timeout  60
tun-mtu-extra 32 
auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
xxx
----END CERTIFICATE-----

</ca>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
xxx
-----END OpenVPN Static key V1-----
</tls-auth>
key-direction 1
route-ipv6 ::/0
route 0.0.0.0 0.0.0.0 vpn_gateway
mssfix
tun-mtu 1532
nobind
verify-x509-name CN=xxx.nordvpn.com
remote-cert-tls server
cipher AES-256-CBC
auth SHA512
persist-tun
# persist-tun also enables pre resolving to avoid DNS resolve problem
preresolve
# Use system proxy setting
management-query-proxy
# Custom configuration options
# You are on your on own here :)
# These options found in the config file do not map to config settings:
ping 15 
reneg-sec 0 
ping-restart 0 
ping exit
resolv-retry infinite 
fast-io 
auth-nocache 




```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by schwabe** [comment]
The Packet ID error /replay is an indication of network problems and not a bug.
