### ISSUE TITLE
Editing Profile results in NullPointerException (v0.7.47)

### ISSUE THREAD

**Issue by Admincore-AppDev** [schwabe/ics-openvpn#1624]
1. Android 11 (Not Rooted)
2. LineageOS 18.1 (20230218)
3. Google Nexus 5 (hammerhead)
4. v0.7.47 (VersionCode: 202 | Source: plai.de)
 
# Description of the issue
@schwabe i have to make another issue report. The new App release is crashing with a NullPointerException while trying to editing the VPN-Profile options: "SERVER LIST",  "IP AND DNS" and "ROUTNG". See the video below: 

https://github.com/schwabe/ics-openvpn/assets/139226997/7f1e2bd1-72f2-45f8-8a0b-c8b5be32725a

I am pretty sure you are already aware of this issue, if not i hope the report is enough for you, idk how to get more verbosity.

The App itself works pretty flawless for now, this seems the only fatal issue. I need the editing for change the "proto udp4/6" options, otherwise this wouldn't annoying me. ;-)
# Trace-Log
```
FATAL EXCEPTION: main
Process: de.blinkt.openvpn, PID: 15547
java.lang.NullPointerException
	at de.blinkt.openvpn.fragments.Settings_IP.bindPreferences(Settings_IP.kt:50)
	at de.blinkt.openvpn.fragments.Settings_IP.onViewCreated(Settings_IP.kt:45)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1751)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:249)
	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
	at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:669)
	at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
	at androidx.viewpager.widget.ViewPager.setCurrentItem(ViewPager.java:612)
	at com.google.android.material.tabs.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:3418)
	at com.google.android.material.tabs.TabLayout.dispatchTabSelected(TabLayout.java:1907)
	at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1900)
	at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1860)
	at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2303)
	at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2493)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by schwabe** [comment]
Thanks for reporting this!
