### ISSUE TITLE
java.lang.NoClassDefFoundError: de.blinkt.openvpn.core.NativeUtils

### ISSUE THREAD

**Issue by shahzad1** [schwabe/ics-openvpn#1636]
FATAL EXCEPTION: OpenVPNServiceCommandThread

                                                                                                    java.lang.NoClassDefFoundError: de.blinkt.openvpn.core.NativeUtils
                                                                                                    	at de.blinkt.openvpn.core.VPNLaunchHelper.writeMiniVPN(VPNLaunchHelper.java:29)
                                                                                                    	at de.blinkt.openvpn.core.VPNLaunchHelper.buildOpenvpnArgv(VPNLaunchHelper.java:56)
                                                                                                    	at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:965)
                                                                                                    	at de.blinkt.openvpn.core.OpenVPNService.lambda$onStartCommand$1$de-blinkt-openvpn-core-OpenVPNService(OpenVPNService.java:843)
                                                                                                    	at de.blinkt.openvpn.core.OpenVPNService$$ExternalSyntheticLambda2.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libovpnutil.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at de.blinkt.openvpn.core.NativeUtils.<clinit>(NativeUtils.java:48)
                                                                                                    	at de.blinkt.openvpn.core.VpnStatus.logInformation(VpnStatus.java:244)
                                                                                                    	at de.blinkt.openvpn.core.VpnStatus.<clinit>(VpnStatus.java:210)
                                                                                                    	at de.blinkt.openvpn.core.VpnStatus.addStateListener(Unknown Source:0)
                                                                                                    	at de.blinkt.openvpn.core.OpenVPNService.onStartCommand(OpenVPNService.java:806)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4799)
                                                                                                    	at android.app.ActivityThread.access$2100(ActivityThread.java:271)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2172)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8319)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

**Comment by schwabe** [comment]
You somehow failed to build the NDK part of the project. See other issues about this
