### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 

### ISSUE THREAD

**Issue by Arunachalamkalimuthu** [schwabe/ics-openvpn#1677]
**Issue Description:**
A non-fatal `NullPointerException` is occurring consistently on specific devices in production when attempting to invoke the `checkProfile` method of the `VpnProfile` class. This issue is leading to crashes for many users.

**Exception Stack Trace:**
```java
Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int de.blinkt.openvpn.VpnProfile.checkProfile(android.content.Context)' on a null object reference
       at android.os.Parcel.createException(Parcel.java:1956)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at de.blinkt.openvpn.api.IOpenVPNAPIService$Stub$Proxy.startProfile(IOpenVPNAPIService.java:317)

**Comment by schwabe** [comment]
This bug report sounds like it is outside my app. You are saying "many users" but I don't think you are meaning my users as I do not have this crash report in my Play Console.
