### ISSUE TITLE
Allow to connect to a VPN server passing ovpn file path (in device's storage) and credentials parameters through api (adb)

### ISSUE THREAD

**Issue by jefftrigueiro** [schwabe/ics-openvpn#1690]
It would be very nice if we don't have to save a profile in the app to connect to a VPN server.

Something like:

`adb -d shell am start -a android.intent.action.MAIN -n de.blinkt.openvpn/.api.ConnectVPN --es de.blinkt.openvpn.api.ovpnPath /sdcard/myVPNs/vpn1.ovpn --es de.blinkt.openvpn.api.username my_username --es de.blinkt.openvpn.api.password my_password`

Thanks in advance.

**Comment by schwabe** [comment]
Why do you need that via adb? There is already an API (AIDL) that another app can use to do that. Also on newer Android versions, directly accessing the sdcard is almost impossible without user intervention anyway, so implementing this would only really work on older Android versions.

**Comment by jefftrigueiro** [comment]
@schwabe so, through AIDL can I use the ovpn file to connect to a VPN server passing it as a parameter with the credentials too? Without the need to import it?

**Comment by schwabe** [comment]
Yes. Check `IOpenVPNAPIService` and also the remoteExample app in the repo. Especially this method:

```
	/** start a profile using a config as inline string. Make sure that all needed data is inlined,
	 * e.g., using <ca>...</ca> or <auth-user-pass>...</auth-user-pass>
	 * See the OpenVPN manual page for more on inlining files */
	void startVPN (in String inlineconfig);
```

**Comment by jefftrigueiro** [comment]
Hello @schwabe 
I have created a simple app to try out the remoteApp way, but I'm having some problems:

I am following the same flow that you did in MainFragment:

1. Bind the service
2. Check the permission for my app: `mService?.prepare(packageName)`
3. In `onActivityResult()` I try to start the VPN server with `mService!!.startVPN(config.toString())`

But I'm getting the following error: 
`FATAL EXCEPTION: main
                                                                                                    Process: com.trigger.litevpn, PID: 11098
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at de.blinkt.openvpn.api.IOpenVPNAPIService$Stub$Proxy.startVPN(IOpenVPNAPIService.java:300)
                                                                                                    	at com.trigger.litevpn.MainActivity.startVpn(MainActivity.kt:142)
                                                                                                    	at com.trigger.litevpn.MainActivity.onActivityResult(MainActivity.kt:155)
                                                                                                    	at com.trigger.litevpn.MainActivity$mConnection$1.onServiceConnected(MainActivity.kt:90)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2198)
                                                                                                    	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2231)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)`

This error is happening in the class `IOpenVPNAPIService` generated by the AIDL:

`@Override public void startVPN(java.lang.String inlineconfig) throws android.os.RemoteException
      {
        android.os.Parcel _data = android.os.Parcel.obtain();
        android.os.Parcel _reply = android.os.Parcel.obtain();
        try {
          _data.writeInterfaceToken(DESCRIPTOR);
          _data.writeString(inlineconfig);
          boolean _status = mRemote.transact(Stub.TRANSACTION_startVPN, _data, _reply, 0);
          _reply.readException();
        }
        finally {
          _reply.recycle();
          _data.recycle();
        }
      }`

I don't know what I'm doing wrong. I tried with your test.conf file and with another vaild ovpn file.
Can you please help me?
Thanks in advance.

**Comment by executed** [comment]
Though really hacky, unsecure, but somewhat reliable I accomplished **something similar** with following (ROOT access).

I was able to programmatically switch IPs of currently connected profile in OpenVPN given the credentials and other stuff stays the same (ports should stay the same too, but this approach might invlove them too).

I don't recommend this to anyone, I'm basically showing right now how to disable certain setting in the app that when enabled saves you from one of attack vectors. Setting is called "Try to encrypt profiles on storage" and it's ON by default so mad respect for this to Arne!

I've tried everything I could find everywhere to accomplish this using normal OpenVPN API, but I failed. All top notch AIs also failed to help me. Lack of Android development experience and seeing poor **jefftrigueiro** trying to do this via AIDL gave me signal that it's time to do some reverse enginnering kind of stuff.

Here are my steps:
- disabled FS encryption (Setting is called "Try to encrypt profiles on storage");
- imported .ovpn file in OpenVPN app and named it ABC;
- IPs in server list config of profile need to be initially normalized like this (001.001.001.001 instead of 1.1.1.1);
- What to do on auth. fail - ignore, retry;
- Fill in username/password;
- created Termux script that does following:
- disconnects OpenVPN connection using intent;
- force stops OpenVPN app;
- python gets IP that it wants OpenVPN to next;
- python finds associated OpenVPN profile file (.vp) under /data/data/de.blinkt.openvpn/files;
- python dumps .vp contents in binary representation;
- python keeps track of what IP is currently in profile;
- analyzes what HEX value it corresponds to;
- python analyzes HEX for new IP that should go there;
- replaces all occurences of old IP HEX with new IP HEX;
- re-constructs .vp file back to format it was before (initially weird mix of UTF-8 & something);
- removes all the trash files created in the process;
- uses OpenVPN intent to start OpenVPN connection by provided profile name ABC;

My use case is calling ProtonVPN API to find entry IP of least loaded server in particular country and use it to start the OpenVPN profile connection.
I can share the script if someone is interested.

Honestly, I better have spent my time on actually developing the right intent for this project. It is what it is.

**Comment by schwabe** [comment]
The AIDL remote API should also be able to accomplish changing profile. The remote Example in this repository would be a good starting point for that.

**Comment by jefftrigueiro** [comment]
Last year I was able to use the AIDL remote API and I developed a way to pass the inline config (content of the .ovpn file) through adb and get it on my app to connect with the server.
