### ISSUE TITLE
Unhandled exception ErrnoException listen failed: Invalid argument

### ISSUE THREAD

**Issue by sarmadalij** [schwabe/ics-openvpn#1711]
# Unhandled exception: listen failed: EINVAL (Invalid argument)

I was using it on Graphene OS as normally install it was working fine. but when I set it as pre-installed the following issue occurs when ever i am connecting/running the vpn service. Device information is also there.
Also note that i have set other apps as pre installed as the same way as this app, Other apps are working fine but only this app is causing the issue.

```
2024-04-30 13:38:16 built by CN=GrapheneOS (FP: bd:11:e6:8e:fe:0d:33:6f:9c:d2:16:d2:b6:91:0e:35:b3:2f🇩🇪8c:59:44:eb:09:0b:4d:cb:42:fe:6e:60:fb) 0.7.51 running on google Pixel 6a (bluejay), Android 14 (UQ1A.240105.002) API 34, ABI arm64-v8a, (google/bluejay/bluejay:14/UQ1A.240105.002/2024013000:user/release-keys)
2024-04-30 13:38:17 Building configuration…
2024-04-30 13:38:17 Restarting OpenVPN Service (App crashed probably crashed or killed for memory pressure)
2024-04-30 13:38:23 Building configuration…
2024-04-30 13:38:23 Fetched VPN profile (imported profiles from AS) triggered by main profile list
2024-04-30 13:38:23 Scheduling VPN keep alive for VPN imported profiles from AS
2024-04-30 13:38:25 Unhandled exception: listen failed: EINVAL (Invalid argument)

java.io.IOException: listen failed: EINVAL (Invalid argument)
at android.net.LocalSocketImpl.listen(LocalSocketImpl.java:286)
at android.net.LocalServerSocket.<init>(LocalServerSocket.java:68)
at de.blinkt.openvpn.core.OpenVpnManagementThread.openManagementInterface(OpenVpnManagementThread.java:145)
at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:703)
at de.blinkt.openvpn.core.OpenVPNService.lambda$onStartCommand$2(OpenVPNService.java:550)
at de.blinkt.openvpn.core.OpenVPNService.$r8$lambda$T-Dsehw7mwNrBu25oDY3B9NDZdE(Unknown Source:0)
at de.blinkt.openvpn.core.OpenVPNService$$ExternalSyntheticLambda17.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.system.ErrnoException: listen failed: EINVAL (Invalid argument)
at libcore.io.Linux.listen(Native Method)
at libcore.io.ForwardingOs.listen(ForwardingOs.java:459)
at libcore.io.ForwardingOs.listen(ForwardingOs.java:459)
at android.system.Os.listen(Os.java:429)
at android.net.LocalSocketImpl.listen(LocalSocketImpl.java:284)
... 11 more
```
 
waiting for your suggestions.

**Comment by schwabe** [comment]
I have no idea what setting a pre-installed actually does but it looks like it messes with some integral part of the app related to the unix domain socket. I cannot really help with that.
