### ISSUE TITLE
NullPointerException: App Crashes When Invoking IOpenVPNAPIService Methods via Button Click in MainFragment

### ISSUE THREAD

**Issue by TouqeerJavaid** [schwabe/ics-openvpn#1757]
Whenever I call any method of the IOpenVPNAPIService interface by clicking a button in MainFragment, the app crashes. Initially, remoteExample was working fine, and I confirmed this by successfully connecting to the server. However, the issue suddenly started occurring. To double-check, I cloned a new version of the project and tested it, but the same crash occurs.

Android 13
Pixel 4

FATAL EXCEPTION: main
                                                                                                    Process: de.blinkt.openvpn.remote, PID: 20626
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
                                                                                                    	at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:297)
                                                                                                    	at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:274)
                                                                                                    	at android.view.View.performClick(View.java:7455)
                                                                                                    	at android.view.View.performClickInternal(View.java:7432)
                                                                                                    	at android.view.View.access$3700(View.java:835)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28810)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by schwabe** [comment]
Is this reproducible with the remoteExample or is that already your code based on that example?

**Comment by TouqeerJavaid** [comment]
It is reproduceable with remoteExample. Simply clone project and run remoteExample this crash will happened.

**Comment by coltEli** [comment]
@TouqeerJavaid did you rebuild main after recloning? I was seeing the same message by debugging remoteExample straight away until I successfully built main.
