### ISSUE TITLE
`FATAL EXCEPTION: main` when opening the `Advanced` section of the active profile

### ISSUE THREAD

**Issue by 532910** [schwabe/ics-openvpn#1769]
Trying to open the Advanced section of the active (connected) profile causes the application to crash:

```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: de.blinkt.openvpn, PID: 29507
E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property mUsePull has not been initialized
E AndroidRuntime:       at de.blinkt.openvpn.fragments.Settings_IP.saveSettings(Settings_IP.kt:93)
E AndroidRuntime:       at de.blinkt.openvpn.fragments.OpenVpnPreferencesFragment.onSaveInstanceState(OpenVpnPreferencesFragment.java:57)
E AndroidRuntime:       at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3318)
E AndroidRuntime:       at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:722)
E AndroidRuntime:       at androidx.fragment.app.FragmentStateManager.saveInstanceState(FragmentStateManager.java:760)
E AndroidRuntime:       at androidx.fragment.app.FragmentManager.saveFragmentInstanceState(FragmentManager.java:1479)
E AndroidRuntime:       at androidx.viewpager2.adapter.FragmentStateAdapter.removeFragment(FragmentStateAdapter.java:468)
E AndroidRuntime:       at androidx.viewpager2.adapter.FragmentStateAdapter.onViewRecycled(FragmentStateAdapter.java:414)
E AndroidRuntime:       at androidx.viewpager2.adapter.FragmentStateAdapter.onViewRecycled(FragmentStateAdapter.java:73)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$Recycler.dispatchViewRecycled(RecyclerView.java:7415)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(RecyclerView.java:7177)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleCachedViewAt(RecyclerView.java:7057)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:7105)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:7007)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:9741)
E AndroidRuntime:       at androidx.recyclerview.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1464)
E AndroidRuntime:       at androidx.recyclerview.widget.LinearLayoutManager.recycleViewsFromStart(LinearLayoutManager.java:1514)
E AndroidRuntime:       at androidx.recyclerview.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1589)
E AndroidRuntime:       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1613)
E AndroidRuntime:       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425)
E AndroidRuntime:       at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1145)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2047)
E AndroidRuntime:       at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5835)
E AndroidRuntime:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
E AndroidRuntime:       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
E AndroidRuntime:       at android.view.Choreographer.doCallbacks(Choreographer.java:899)
E AndroidRuntime:       at android.view.Choreographer.doFrame(Choreographer.java:827)
E AndroidRuntime:       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
E AndroidRuntime:       at android.os.Handler.handleCallback(Handler.java:942)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:       at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:7930)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

0.7.53 (208) from f-droid, op9pro, crDroid 9.7 on android 13

**Comment by 532910** [comment]
possibly related: https://github.com/schwabe/ics-openvpn/issues/1754

**Comment by schwabe** [comment]
Should be fixed in the latest commit.
