### ISSUE TITLE
PreBuild OpenVpn as SystemApp throw /system/app/openvpn/lib/arm64/libovpnexec.so No such file

### ISSUE THREAD

**Issue by HanselLi** [schwabe/ics-openvpn#1773]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version  : 11
2. Android Vendor/Custom ROM 
3. Device
4. Version of the app (version number/play store version/self-built)
 0.7.53
# Description of the issue
**PreBuild OpenVpn as SystemApp , but it crash when pull up by third app , it show can not find the libovpnexec.so , i  put the openvpn.apk to ROM prebuild system app dir , and the android.mk file is below** 

```
#  Copyright (c) 2016 The Linux Foundation. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#     # Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     # Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     # Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
#  OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
#  IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE        := TerminalClient
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := platform
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES     := TerminalClient.apk
LOCAL_DEX_PREOPT    := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := TerminalDevice
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := platform
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES     := TerminalDevice.apk
LOCAL_DEX_PREOPT    := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := TerminalLauncher
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := platform
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES     := TerminalLauncher.apk
LOCAL_DEX_PREOPT    := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := TerminalAlgor
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := platform
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES     := TerminalAlgor.apk
LOCAL_DEX_PREOPT    := false
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE        := openvpn
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := APPS
LOCAL_CERTIFICATE   := platform
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_SRC_FILES     := openvpn.apk
LOCAL_DEX_PREOPT    := false
include $(BUILD_PREBUILT)

```

# Log (if applicable)
```
U#��X������<iU��X������lUn��X������QFetched VPN profile (sandstar) triggered by external OpenVPN service by uid: 1000UG��X��
����*Scheduling VPN keep alive for VPN sandstarU2��X������started Socket ThreadUl��X�����������seCannot run program "/system/app/o
penvpn/lib/arm64/libovpnexec.so": error=2, No such file or directorys�java.io.IOException: Cannot run program "/system/app/openvpn/lib/arm64/libovpnexec.so": error= 2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:134)
        at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:76)
        at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.VNIXProcess.forkAndExec(Native Method)
        at java.lang.VNIXProcess.<init>(VNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 3 more
s,Error reading from output of OpenVPN processU5��X�����������s^Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null objec
t references�java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference
        at de.blinkt.openvpn.core.OpenVPNThread.stopProcess(OpenVPNThread.java:64)
        at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:185)
        at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:76)
```
log contents
```

# Configuration file

```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by schwabe** [comment]
This might be very well the case. Why do you need to build OpenVPN for Android as system app?

**Comment by HanselLi** [comment]
because we need custom it as system app , our android device is custom ROM used for IOT things . pls help me

**Comment by schwabe** [comment]
That sounds like a commercial product. I do not provide consulting for commercial products for free. 

And installing the app as system app is also not something that fits into the normal use case of the app. I could advise and work with you on that and spend time and figuring out what is going wrong. But expecting me to reproduce your for issue and solving that issue, which is has no or little benefit to anyone else, for free is not reasonable.

Executing of the OpenVPN binary on Android has always been finicky, so without taking a closer look and spending time, there is not really much that I can do to help you.
