### ISSUE TITLE
Crash on rotation while in `server list` or `routing`

### ISSUE THREAD

**Issue by ValdikSS** [schwabe/ics-openvpn#1775]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: **10**
2. Android Vendor/Custom ROM: **Stock OS from LG**
3. Device: **LG V50**
4. Version of the app (version number/play store version/self-built): **0.7.53 f-droid**
 
# Description of the issue

1. Enter configuration editing mode
2. Go to server list or routing tab
3. Rotate the device

The application crashes.

# Log (if applicable)

```
12-04 18:34:11.750  5830  5830 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-04 18:34:11.753  5830  5830 E AndroidRuntime: FATAL EXCEPTION: main
12-04 18:34:11.753  5830  5830 E AndroidRuntime: Process: de.blinkt.openvpn, PID: 5830
12-04 18:34:11.753  5830  5830 E AndroidRuntime: kotlin.UninitializedPropertyAccessException: lateinit property mUsePull has not been initialized
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at de.blinkt.openvpn.fragments.Settings_IP.saveSettings(Settings_IP.kt:93)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at de.blinkt.openvpn.fragments.OpenVpnPreferencesFragment.onSaveInstanceState(OpenVpnPreferencesFragment.java:57)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3318)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:722)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:217)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2664)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.lambda$attachController$5$androidx-fragment-app-FragmentManager(FragmentManager.java:2941)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda4.saveState(D8$$SyntheticClass:0)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.kt:345)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at de.blinkt.openvpn.activities.VPNPreferences.onSaveInstanceState(VPNPreferences.kt:53)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.Activity.performSaveInstanceState(Activity.java:2042)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1486)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5412)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4704)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5360)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5295)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7573)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-04 18:34:11.753  5830  5830 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
```

**Comment by ValdikSS** [comment]
#1769 #1754

**Comment by schwabe** [comment]
As you already noticed yourself, this is a duplicate.
