### ISSUE TITLE
0 bit/s occasional error 

### ISSUE THREAD

**Issue by spjps2009** [schwabe/ics-openvpn#457]
Hi occasionally openvpn android shows 0bit/s and this is error in logs 

Failed to retrieve fd from socket (null): null receiver

java.lang.NullPointerException: null receiver
    at java.lang.reflect.Method.invoke(Native Method)
    at de.blinkt.openvpn.core.OpenVpnManagementThread.protectFileDescriptor(OpenVpnManagementThread.java:163)
    at de.blinkt.openvpn.core.OpenVpnManagementThread.processNeedCommand(OpenVpnManagementThread.java:402)
    at de.blinkt.openvpn.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:221)
    at de.blinkt.openvpn.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:189)
    at de.blinkt.openvpn.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:146)
    at java.lang.Thread.run(Thread.java:818)

**Comment by schwabe** [comment]
Could you provide more log ouptut from app? I.e. what happens before that error.

**Comment by spjps2009** [comment]
Here's the full log: http://pastebin.com/REXYF7cp

**Comment by schwabe** [comment]
Cannot reproduce, bug probably not present anymore
