### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by Jhon-wu** [schwabe/ics-openvpn#463]
your project code can't compile success! it is lost some library？

**Comment by Jhon-wu** [comment]
03-18 21:37:43.615 31011-31011/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: de.blinkt.openvpn, PID: 31011
                                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.blinkt.openvpn-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libopvpnutil.so"
                                                                       at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                       at java.lang.System.loadLibrary(System.java:988)
                                                                       at de.blinkt.openvpn.core.NativeUtils.<clinit>(NativeUtils.java:22)
                                                                       at de.blinkt.openvpn.core.VpnStatus.logInformation(VpnStatus.java:417)
                                                                       at de.blinkt.openvpn.core.VpnStatus.<clinit>(VpnStatus.java:206)
                                                                       at de.blinkt.openvpn.core.ICSOpenVPNApplication.onCreate(ICSOpenVPNApplication.java:40)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4569)
                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:154)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:135)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5279)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)

**Comment by xDragonZ** [comment]
There's no issue with this project, please read "readme"

**Comment by schwabe** [comment]
As @xDragonZ says.

**Comment by braj24** [comment]
I am also getting the same error as @Jhon-wu  and i read readme text also.I am not getting anything from that file.
I am running API 23 in my phone.
please help.
Thank you

**Comment by braj24** [comment]
09-27 16:34:45.046 30241-30428/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-2107
                                                                   Process: de.blinkt.openvpn, PID: 30241
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.core.VPNLaunchHelper.writeMiniVPN(VPNLaunchHelper.java:38)
                                                                       at de.blinkt.openvpn.core.VPNLaunchHelper.buildOpenvpnArgv(VPNLaunchHelper.java:79)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:420)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:58)
                                                                       at de.blinkt.openvpn.core.OpenVPNService$2.run(OpenVPNService.java:388)
                                                                       at java.lang.Thread.run(Thread.java:818)
09-27 16:34:45.047 783-799/? W/ActivityManager:   Force finishing activity 1 de.blinkt.openvpn/.activities.LogWindow

**Comment by schwabe** [comment]
@braj24 You did not follow the build steps

**Comment by avinashlb** [comment]
As @xDragonZ  says
