### ISSUE TITLE
va.lang.UnsatisfiedLinkError: com.bestvpn.core.NativeUtils

### ISSUE THREAD

**Issue by robinbestvpn** [schwabe/ics-openvpn#479]
Hi, Whenever I am trying to run, I am getting following error

```
   Process: com.bestvpn, PID: 2451
                                                                            java.lang.UnsatisfiedLinkError: com.bestvpn.core.NativeUtils
                                                                                at com.bestvpn.VpnProfile.getConfigFile(VpnProfile.java:277)
                                                                                at com.bestvpn.VpnProfile.writeConfigFile(VpnProfile.java:660)
                                                                                at com.bestvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:406)
                                                                                at com.bestvpn.core.OpenVPNService.access$200(OpenVPNService.java:60)
                                                                                at com.bestvpn.core.OpenVPNService$2.run(OpenVPNService.java:386)
                                                                                at java.lang.Thread.run(Thread.java:818)
```

**Comment by schwabe** [comment]
I already told you in the last issue that you need to read the README how to build the project and build the project.

Please also note that you **must** publish your fork Open Source since this project is under the GPL. (I see a com.bestvpn in there)
