### ISSUE TITLE
Crash on import .opvn file

### ISSUE THREAD

**Issue by giorizzotti** [schwabe/ics-openvpn#486]
I've a Samsung Note 4, I'm trying to import several .opvn file downloaded from free OpenVpn website. When I try to connect, the app crashs.

**Comment by schwabe** [comment]
can you give one of the configuration files, so I can check what is happening?

**Comment by giorizzotti** [comment]
Here is a zip file with several .opvn file. Some of them requires username and password, you can find it on the service's website. Thank you.
[opvn.zip](https://github.com/schwabe/ics-openvpn/files/254128/opvn.zip)

**Comment by schwabe** [comment]
Which of these files does crash the app? All of them?

**Comment by giorizzotti** [comment]
Yes, all of them!

**Comment by schwabe** [comment]
I just tested them all, they all import fine. How are you importing them?

**Comment by giorizzotti** [comment]
Yes, the import procedure is ok, but when I try to connect to one of them, the application crash.

**Comment by schwabe** [comment]
I tried the vpngate_... configuration it works fine. How exactly does the app crash for you?

**Comment by giorizzotti** [comment]
![screenshot_2016-05-09-10-32-20](https://cloud.githubusercontent.com/assets/11563183/15107741/d665fcfc-15d1-11e6-8d59-efcae3ba37ba.png)

**Comment by bzour94** [comment]
I have the same problem , after importing the .opvn file and try to connect to it the application crash , there is two more crashes , when you click on edit and go to "allowing apps" or "generated config" tabs its crash 
logcat when trying to connect :
05-09 22:04:00.161 28068-28165/de.blinkt.openvpn I/art: Rejecting re-init on previously-failed class java.lang.Class<de.blinkt.openvpn.core.NativeUtils>
05-09 22:04:00.161 28068-28165/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-27415
                                                                   Process: de.blinkt.openvpn, PID: 28068
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:276)
                                                                       at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:649)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:410)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:60)
                                                                       at de.blinkt.openvpn.core.OpenVPNService$2.run(OpenVPNService.java:390)
                                                                       at java.lang.Thread.run(Thread.java:818)

logcat when click on "Generated config" :

05-09 22:04:51.551 29137-29281/de.blinkt.openvpn I/art: Rejecting re-init on previously-failed class java.lang.Class<de.blinkt.openvpn.core.NativeUtils>
05-09 22:04:51.551 29137-29281/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-27471
                                                                   Process: de.blinkt.openvpn, PID: 29137
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:276)
                                                                       at de.blinkt.openvpn.fragments.ShowConfigFragment$2.run(ShowConfigFragment.java:54)

logcat when click on "Allowed apps" :

05-09 22:05:59.981 30128-30479/de.blinkt.openvpn I/art: Rejecting re-init on previously-failed class java.lang.Class<de.blinkt.openvpn.core.NativeUtils>
05-09 22:05:59.981 30128-30479/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-27462
                                                                   Process: de.blinkt.openvpn, PID: 30128
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:276)
                                                                       at de.blinkt.openvpn.fragments.ShowConfigFragment$2.run(ShowConfigFragment.java:54)

Edit : i try to install the application from play store and use the same .opvn file , everything works well

**Comment by schwabe** [comment]
@qaismenawi that is a different issue Read the README how to build ics-openvpn, you are missing the native libraries.

**Comment by schwabe** [comment]
@giorizzotti which version of the app are you running?

**Comment by giorizzotti** [comment]
@schwabe I'm using the last from your repository, but maybe the issues is the same of the @qaismenawi  one, because I just opened the project on Android Studio and runned with the smartphone connected.

**Comment by schwabe** [comment]
@giorizzotti same goes for you than as for @qaismenawi
