### ISSUE TITLE
I get error like No implementation found for java.lang.String com.proxyserver.provpn.core.NativeUtils.getNativeAPI() 

### ISSUE THREAD

**Issue by yagneshshinde** [schwabe/ics-openvpn#493]
`FATAL EXCEPTION: main
                                                                        Process: com.proxyserver.provpn, PID: 12408
                                                                        java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.proxyserver.provpn.core.NativeUtils.getNativeAPI() (tried Java_com_proxyserver_provpn_core_NativeUtils_getNativeAPI and Java_com_proxyserver_provpn_core_NativeUtils_getNativeAPI__)
                                                                            at com.proxyserver.provpn.core.NativeUtils.getNativeAPI(Native Method)
                                                                            at com.proxyserver.provpn.core.VpnStatus.logInformation(VpnStatus.java:158)
                                                                            at com.proxyserver.provpn.core.VpnStatus.<clinit>(VpnStatus.java:71)
                                                                            at com.proxyserver.provpn.core.ICSOpenVPNApplication.onCreate(ICSOpenVPNApplication.java:62)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                                            at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

here i change the package name in JNI files also but the same issue

**Comment by schwabe** [comment]
Just keep the package name of the de.blinkt.openvpn.core.\* classes.

**Comment by yagneshshinde** [comment]
But i need to change package name for my application. Do i need to changes in .mk or any other files?

**Comment by schwabe** [comment]
there is really no need to change the package name. 

You can have 

de.blinkt.openvpn.\* files in a project that is com.foo.app

Beside from that, from my experience the kind of type you are building (custom VPN provider app) usually violates license and the GPL, so I am very reluctant to help unless you convince me otherwise.
