### ISSUE TITLE
I get error like  No implementation found for java.lang.String com.open.myvpn.core.NativeUtils.getNativeAPI() (tried Java_com_open_myvpn_core_NativeUtils_getNativeAPI and Java_com_open_myvpn_core_NativeUtils_getNativeAPI__)

### ISSUE THREAD

**Issue by iamrama** [schwabe/ics-openvpn#500]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
# Description of the issue

**Comment by iamrama** [comment]
No implementation found for java.lang.String com.open.myvpn.core.NativeUtils.getNativeAPI() (tried Java_com_open_myvpn_core_NativeUtils_getNativeAPI and Java_com_open_myvpn_core_NativeUtils_getNativeAPI__)
06-13 14:02:59.114 28400-2914/com.open.myvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-185688
                                                                   Process: com.open.myvpn, PID: 28400
                                                                   java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.open.myvpn.core.NativeUtils.getNativeAPI() (tried Java_com_open_myvpn_core_NativeUtils_getNativeAPI and Java_com_open_myvpn_core_NativeUtils_getNativeAPI__)
                                                                       at com.open.myvpn.core.NativeUtils.getNativeAPI(Native Method)
                                                                       at com.open.myvpn.core.VpnProfile.getConfigFile(VpnProfile.java:269)
                                                                       at com.open.myvpn.core.VpnProfile.writeConfigFile(VpnProfile.java:643)
                                                                       at com.open.myvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:404)
                                                                       at com.open.myvpn.core.OpenVPNService.access$200(OpenVPNService.java:54)
                                                                       at com.open.myvpn.core.OpenVPNService$2.run(OpenVPNService.java:384)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by schwabe** [comment]
Duplicate of #493
