### ISSUE TITLE
when i import your project，and run in the emulator，edit the password and username and login ，the Application is bolck。 help me，thank you very much

### ISSUE THREAD

**Issue by furuiCQ** [schwabe/ics-openvpn#503]
FATAL EXCEPTION: Thread-215
                                                                   Process: de.blinkt.openvpn, PID: 17348
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:276)
                                                                       at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:649)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:408)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:58)
                                                                       at de.blinkt.openvpn.core.OpenVPNService$2.run(OpenVPNService.java:388)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by schwabe** [comment]
Duplicate

**Comment by furuiCQ** [comment]
Duplicate  issue id？

**Comment by furuiCQ** [comment]
thank you so much

**Comment by schwabe** [comment]
@furuiCQ with _minimal_ effort you would found one the many duplicate issues for this problem, e.g. #493

**Comment by furuiCQ** [comment]
but my package name is de.blinkt.openvpn.core*.class 
i not change the package name.

**Comment by radeshf** [comment]
same problem, 
also not changing package name at all
