### ISSUE TITLE
I just need to ovpnlibs  all files under

### ISSUE THREAD

**Issue by zhangweiqwe** [schwabe/ics-openvpn#506]
In a country like China, I was unable to open  http://google-breakpad.googlecode.com/svn/trunk/ google-breakpad

ovpnlibs  all files under I need  and I don't have good attention

because

 FATAL EXCEPTION: Thread-3293
                                                                   Process: de.blinkt.openvpn, PID: 22065
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:276)
                                                                       at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:649)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:408)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:58)
                                                                       at de.blinkt.openvpn.core.OpenVPNService$2.run(OpenVPNService.java:388)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by schwabe** [comment]
@zhangweiqwe please stop opening new issues without looking through/searching the closed ones (#365).
