### ISSUE TITLE
de.blinkt.openvpn.core.NativeUtils

### ISSUE THREAD

**Issue by cnsms** [schwabe/ics-openvpn#545]
09-06 14:17:19.750 31142-31201/de.blinkt.openvpn I/OpenGLRenderer: Initialized EGL, version 1.4
09-06 14:17:19.830 31142-31201/de.blinkt.openvpn D/OpenGLRenderer: Enabling debug mode 0
09-06 14:17:20.060 31142-31142/de.blinkt.openvpn I/Choreographer: Skipped 35 frames!  The application may be doing too much work on its main thread.
09-06 14:17:20.240 31142-31142/de.blinkt.openvpn I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1b2307c4 time:7752765
09-06 14:17:30.590 31142-31142/de.blinkt.openvpn I/Timeline: Timeline: Activity_launch_request time:7763116
09-06 14:17:30.690 31142-31142/de.blinkt.openvpn I/art: Rejecting re-init on previously-failed class java.lang.Class<de.blinkt.openvpn.core.NativeUtils>
09-06 14:17:30.700 31142-31142/de.blinkt.openvpn I/Timeline: Timeline: Activity_launch_request time:7763229
09-06 14:17:30.740 31142-31142/de.blinkt.openvpn D/ActivityThreadInjector: clearCachedDrawables.
09-06 14:17:30.760 31142-31785/de.blinkt.openvpn I/art: Rejecting re-init on previously-failed class java.lang.Class<de.blinkt.openvpn.core.NativeUtils>
09-06 14:17:30.760 31142-31785/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-3852
                                                                   Process: de.blinkt.openvpn, PID: 31142
                                                                   java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                       at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:278)
                                                                       at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:660)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:408)
                                                                       at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:58)
                                                                       at de.blinkt.openvpn.core.OpenVPNService$2.run(OpenVPNService.java:388)
                                                                       at java.lang.Thread.run(Thread.java:818)
09-06 14:17:30.780 31142-31785/de.blinkt.openvpn I/Process: Sending signal. PID: 31142 SIG: 9

**Comment by cnsms** [comment]
I haven't changed package name
I just download and run

**Comment by schwabe** [comment]
Still a duplicate, you need to build the native binaries. See the README and the other issues.

**Comment by avinashlb** [comment]
> I haven't changed the package name
> I just download and run

Please check the code
