### ISSUE TITLE
IOException: Bad file number at android.net.LocalSocketImpl.close_native(Native Method)

### ISSUE THREAD

**Issue by VictorJava** [schwabe/ics-openvpn#553]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version = 4.2 \ 5.1
2. Android Vendor/Custom ROM = default
3. Device Sumsung GT-S7272 \ LG G3.
4. Version of the app (version number/play store version/self built) versionCode = 138
   versionName = "0.6.57"
# Description of the issue

Hi Arne, 
I have seen that this similar issue
https://github.com/schwabe/ics-openvpn/issues/408
was closed but as for me it reproduced on both devices. 
It`s occured If you frequently trying to connect...

Could you help me?

There is the stacktrace
E/System: java.io.IOException: Bad file number
                                                              at android.net.LocalSocketImpl.close_native(Native Method)
                                                              at android.net.LocalSocketImpl.close(LocalSocketImpl.java:225)
                                                              at android.net.LocalSocketImpl.finalize(LocalSocketImpl.java:487)
                                                              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
                                                              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
                                                              at java.lang.Thread.run(Thread.java:856)

Thank you.

**Comment by schwabe** [comment]
Can you send me a complete log from the app?

**Comment by VictorJava** [comment]
Hi,  here you are.
![o_vpn_error](https://cloud.githubusercontent.com/assets/8449621/18908127/12ab2a92-8577-11e6-9871-0adfaa8362a2.jpg)

This problerm appeared while vpn going to reconnect.
Thanks for your help.

**Comment by VictorJava** [comment]
Thanks.
