### ISSUE TITLE
Error in VpnProfile

### ISSUE THREAD

**Issue by SFocus** [schwabe/ics-openvpn#579]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 5.0 
2. Android Vendor
3. Device Lg magna 
4. Version of the app 0,6,60
 
# Description of the issue
 
 When I add my config file  I have this error:
```
11-07 12:21:51.064 4932-4962/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: Thread-35573
                                                                 Process: de.blinkt.openvpn, PID: 4932
                                                                 java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                     at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:279)
                                                                     at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:660)
                                                                     at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:408)
                                                                     at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:58)
                                                                     at de.blinkt.openvpn.core.OpenVPNService$2.run(OpenVPNService.java:388)
                                                                     at java.lang.Thread.run(Thread.java:818)
 
```
How to fix? 

[client.txt](https://github.com/schwabe/ics-openvpn/files/575054/client.txt)
**Its my config file. Please help)**

**Comment by schwabe** [comment]
_sigh_ read closed issues, read the readme
