### ISSUE TITLE
Could not get certificate from Keystore

### ISSUE THREAD

**Issue by ashceryth** [schwabe/ics-openvpn#618]
# General information
1. Android Version: 7.1.1
2. Android Vendor/Custom ROM: Custom ROM (DirtyUnicorns 11)
3. Device: OnePlus 3
4. Version of the app (version number/play store version/self built):  0.6.64 (Play Store)
 
# Description of the issue
 
Hi,
I would like to use a certificate from Keytore for connecting to my VPN server. I used the install dialog within the app for importing the cert. After selecting the cert the app displays "Could not get certificate from Keystore (...)" right beneath the certificate alias and connecting is impossible. Reimporting does not solve the problem. Using the PKCS12 directly works.

```
2017-01-29 21:58:17 offizielle Version 0.6.64 läuft auf OnePlus du_oneplus3 (msm8996), Android 7.1.1 (N6F26Q) API 25, ABI arm64-v8a, (OnePlus/du_oneplus3/unknown:7.1.1/N6F26Q/eng.mazda.20170107.063806:userdebug/dev-keys)
2017-01-29 21:58:27 Used x 1 tries to get current version (13/13) of the profile
2017-01-29 21:58:27 Generiere OpenVPN-Konfiguration…
2017-01-29 21:58:27 Fehler beim Zugriff auf den Zertifikatsspeicher: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
2017-01-29 21:58:27 Kann nicht auf die Zertifikate im Android-Zertifikatsspeicher zugreifen. Dies kann durch ein Systemupdate oder durch Zurückspielen der App oder ihrer Einstellungen aus einem Backup hervorgerufen werden. Bitte bearbeiten Sie das VPN und wählen Sie das Zertifikat erneut in den Grundeinstellungen aus, um die Zugriffsberechtigung für das Zertifikat wieder herzustellen.
2017-01-29 21:58:27 started Socket Thread
2017-01-29 21:58:28 Netzwerkstatus: CONNECTED LTE to MOBILE webaut
2017-01-29 21:58:28 P:Initializing Google Breakpad!
2017-01-29 21:58:28 Options error: In /data/user/0/de.blinkt.openvpn/cache/android.conf:20: Maximum optione line length (256) exceeded, line starts with Kann nicht auf die Zertifikate im Android-Zertifikatsspeicher zugreifen. Dies kann durch ein Systemupdate oder durch Zurückspielen der App oder ihrer Einstellungen aus einem Backup hervorgerufen werden. Bitte bearbeiten Sie das VPN und wählen Sie das Zer
2017-01-29 21:58:28 Use --help for more information.
2017-01-29 21:58:28 Process exited with exit value 1
```

**Comment by ashceryth** [comment]
Logcat:

```
01-29 22:25:59.280 I/ActivityManager(2131): START u0 {act=android.intent.action.MAIN cmp=de.blinkt.openvpn/.LaunchVPN (has extras)} from uid XXX on display 0
01-29 22:25:59.436 I/ActivityManager(2131): Displayed de.blinkt.openvpn/.LaunchVPN: +149ms
01-29 22:26:09.675 I/ActivityManager(2131): START u0 {flg=0x20000 cmp=de.blinkt.openvpn/.activities.LogWindow} from uid XXX on display 0
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.VpnProfile.getKeyStoreCertificates(VpnProfile.java:780)
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.VpnProfile.getKeyStoreCertificates(VpnProfile.java:701)
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:388)
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:685)
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:478)
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:64)
01-29 22:26:09.831 W/System.err(6617): 	at de.blinkt.openvpn.core.OpenVPNService$3.run(OpenVPNService.java:453)
01-29 22:26:09.835 I/OpenVPN (6617): Starting openvpn
01-29 22:26:09.857 I/OpenVPN (6617): OpenVPN process exited
```

**Comment by andiwulan** [comment]
Good luck for me...
No shadow kingdom

**Comment by schwabe** [comment]
@ashceryth Does selecting the certificate in the basic settings work?

@andiwulan ??

**Comment by ashceryth** [comment]
@schwabe Yes, selecting works but in the basic settings it immediately says  "Could not get certificate from Keystore (...)"

![openvpn](https://cloud.githubusercontent.com/assets/18515002/22420437/aa6ba2c2-e6e2-11e6-83d3-6e14c75b255a.png)

**Comment by schwabe** [comment]
Looking back at the ```java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key``` that seems like the Keystore itself has problem with your key. You might consider reimporting it under a different name.

**Comment by ashceryth** [comment]
Already tried that. Importing itself always worked without any issue. I will try to import the certificate again via system settings to see if it makes any difference and report back.

**Comment by schwabe** [comment]
That will probably make no difference since my app calls into that and the import is handled by the system. You could also try to delete all certificates.

**Comment by ashceryth** [comment]
I see. Well, I will delete all my imported certs and just reimport the PKCS12. My PKCS12 contains a longer certificate chain (Root CA, Issuing CA, Client) - maybe this is an issue. But it worked fine with Marshmallow back then. Mysterious...

**Comment by ashceryth** [comment]
I just deleted all certs an just imported the PKCS12 for OpenVPN. Same issue as before.

**Comment by schwabe** [comment]
Sorry, it still sounds like a Android problem and I have no idea what to do about this. You can try to regenerate the original cert.

**Comment by ToxicBakery** [comment]
@ashceryth out of curiosity, does your device have an enterprise account on it or if not have you enabled any security like pin entry or swipe unlock etc. I ask because the keystore can be wonky on some devices related to device security.

**Comment by kirelagin** [comment]
I am now having the exact same issue.

~~~~
KeyChain Access error: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
~~~~

What does this even mean? When I go to “User credentials” in the settings, it shows me this credential and “one user key”, “one user certificate”, “one CA certificate”, so it looks like the keychain is pretty happy with that.

Any ideas how I could debug this?

**Comment by schwabe** [comment]
That could mean that the java x509 parser (which is stupid btw.) cannot parse the key it gets from the keystore.

**Comment by kirelagin** [comment]
Okay, this is just insane. I have to key/cert pairs generated using the same script and while one pair works, the other does not.
I’ll let you know when I figure this out.

**Comment by kirelagin** [comment]
Ugh, I dunno, I just regenerated everything from scratch and no longer receive this error.
Although it still does not work, now OpenVPN exits with exit code 139 and nothing else in the log. :(

**Comment by schwabe** [comment]
have you the highest log verbosity (with the slider)?

**Comment by kirelagin** [comment]
No, I could not find the slider 😳. But I added `verb 11` as a custom option. Here is what I’ve got:

~~~~
2017-06-29 16:36:41 OpenVPN 2.5-icsopenvpn [git:icsopenvpn-d51333c645c12713+] android-21-arm64-v8a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jun 26 2017
2017-06-29 16:36:41 library versions: OpenSSL 1.1.0f  25 May 2017, LZO 2.10
2017-06-29 16:36:41 PO_INIT maxevents=1 flags=0x00000002
2017-06-29 16:36:41 MANAGEMENT: Connected to management server at /data/user/0/de.blinkt.openvpn/cache/mgmtsocket
2017-06-29 16:36:41 PO_CTL rwflags=0x0001 ev=3 arg=0x00000000
2017-06-29 16:36:41 PO_WAIT[0,0] fd=3 rev=0x00000001 rwflags=0x0001 arg=0x00000000 
2017-06-29 16:36:41 MANAGEMENT: CMD 'hold release'
2017-06-29 16:36:41 GETADDRINFO flags=0x090b ai_family=0 ai_socktype=2
2017-06-29 16:36:41 PO_CTL rwflags=0x0002 ev=3 arg=0x00000000
2017-06-29 16:36:41 PO_WAIT[0,0] fd=3 rev=0x00000004 rwflags=0x0002 arg=0x00000000 
2017-06-29 16:36:41 PO_CTL rwflags=0x0001 ev=3 arg=0x00000000
2017-06-29 16:36:41 PO_WAIT[0,0] fd=3 rev=0x00000001 rwflags=0x0001 arg=0x00000000 
2017-06-29 16:36:41 MANAGEMENT: CMD 'proxy NONE'
2017-06-29 16:36:41 PO_CTL rwflags=0x0001 ev=3 arg=0x00000000
2017-06-29 16:36:41 PO_WAIT[0,0] fd=3 rev=0x00000001 rwflags=0x0001 arg=0x00000000 
2017-06-29 16:36:41 MANAGEMENT: CMD 'bytecount 2'
2017-06-29 16:36:41 PO_CTL rwflags=0x0001 ev=3 arg=0x00000000
2017-06-29 16:36:41 PO_WAIT[0,0] fd=3 rev=0x00000001 rwflags=0x0001 arg=0x00000000 
2017-06-29 16:36:41 MANAGEMENT: CMD 'state on'
2017-06-29 16:36:41 PO_CTL rwflags=0x0001 ev=3 arg=0x00000000
2017-06-29 16:36:42 PO_INIT maxevents=4 flags=0x00000002
2017-06-29 16:36:42 P:Dump path: /data/data/de.blinkt.openvpn/cache/7accdaa2-a652-4214-99f45b9e-f032d740.dmp
2017-06-29 16:36:42 Process exited with exit value 139
~~~~

**Comment by schwabe** [comment]
@kirelagin when you click the eye symbol in the log window. but that looks like the app is just crashing.

**Comment by kirelagin** [comment]
Yeah, looks like that.

I suspect this might be related to some properties of the certificate, I’ll try later with a an RSA key to make sure that it is not some EC-related issue.

Here is my certificate for the record:

~~~~
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 4 (0x4)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN=OpenVPN CA
        Validity
            Not Before: Jun 29 13:15:52 2017 GMT
            Not After : Jun 27 13:15:52 2027 GMT
        Subject: CN=kirOnePlus
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
            EC Public Key:
                pub:
                    04:30:4e:fa:a7:90:4f:5c:70:24:74:1d:f9:23:f2:
                    2f:84:ff:32:37:1c:02:0c:33:10:17:f0:83:49:71:
                    41:72:1e:b1:1f:7d:15:a8:1b:bb:c5:b1:d2:23:d5:
                    33:f6:73:b4:a0:4c:76:a4:6d:74:c9:16:ba:07:4d:
                    b5:35:9d:f8:f0
                ASN1 OID: prime256v1
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Key Agreement
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            X509v3 Subject Key Identifier:
                AC:53:20:B0:81:37:52:70:07:3E:DB:99:87:3C:34:CB:31:D0:D2:AE
            X509v3 Authority Key Identifier:
                keyid:CF:0A:E3:96:E0:10:E0:FC:D5:FD:FB:3E:4C:5E:01:1E:F8:E3:66:B4
                DirName:/CN=OpenVPN CA
                serial:C7:D8:AF:79:33:1B:E8:3F

    Signature Algorithm: ecdsa-with-SHA256
        30:46:02:21:00:e1:b1:d6:c1:52:21:78:25:b7:8b:f5:ae:29:
        09:5c:20:ab:bb:8b:32:3e:91:11:0c:08:f3:22:ab:76:ce:0e:
        55:02:21:00:8e:f6:8f:83:55:55:0e:99:a8:46:45:e8:95:29:
        37:24:56:9a:27:5b:4d:4d:ce:fc:3c:41:6f:60:4a:13:6d:bf
~~~~

I should probably also note that those same cert and key work just fine when I choose them as separate files. I also checked the generated config and made sure that the certificate (it gets read from the Keychain and inlined in the config) was right.
