### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by LQG24** [schwabe/ics-openvpn#651]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1、Android 6.0.1
2、Vendor: Samsung
3、Device: SM-G900H
4、Version of the app: 0.6.65 (self built)
 
# Description of the issue
 
 AndroidRuntime: FATAL EXCEPTION: Thread-18318
java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                                             at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:293)
                                                                             at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:685)
                                                                             at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:482)
                                                                             at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:64)
                                                                             at de.blinkt.openvpn.core.OpenVPNService$3.run(OpenVPNService.java:457)
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by schwabe** [comment]
Duplicate. (https://github.com/schwabe/ics-openvpn/issues?utf8=✓&q=UnsatisfiedLinkError)
