### ISSUE TITLE
Everytime I change my allowed apps do I need to reconnect to the VPN again?

### ISSUE THREAD

**Issue by nagendra52** [schwabe/ics-openvpn#654]
1. Android Version--6.0.1
2. Android Vendor/Custom ROM-Nexus 5 STOCK
3. Device-LG Nexus 5
4. Version of the app (version number/play store version/self built)-Play Store latest
 
# Description of the issue

After importing the  profile,I connected to the VPN Server and the VPN connection was successful.

Later I decided to block some apps from going into the VPN Server.So I made changes in the allowed app.But Still the usage of the app is going to the VPN Server.

If I reconnect to the VPN Server again,then the usage of the app is not going to the VPN Server ,which is the desired functionality.

My question is everytime I Change my preferences of Allowed apps,do I need to reconnect to the VPN Server?.

**Comment by schwabe** [comment]
Yes currently you need to reconnect to changed the allowed apps.

**Comment by batman09** [comment]
@schwabe Can you please elaborate on reconnecting to VPN in your above statement. Does reconnect here mean disconnect from VPN server completely and connect again ??[ here the android vpn key symbol disappear and appear after a while ]. But  I have a scenario like I always need to have connection with my VPN server though I alter my allowed apps list. May I know if there are any utility classes in ics-openvpn so  that I can refresh VPN connection without losing connectivity. 

And also when I connect to VPN [ click ok in Android VPN dialog ] it takes on average 7 seconds  for android vpn key symbol to appear in my phone. May I know if there is any way I can reduce this time.

Thanks.

**Comment by schwabe** [comment]
@batman09 there is no utility class for that. Connect speed depends heavily on VPN server/connection. I have VPNs that connect in <2s.

Complete reconnect at the moment.

**Comment by batman09** [comment]
@schwabe Thanks for your response. After your advise we tried with https://play.google.com/store/apps/details?id=net.openvpn.openvpn&hl=en and found that we could connect to our VPN  in almost 2s. Please let me know if we are  missing something here  .Below is my vpn server ovpn file.
```
###############################################################################
# OpenVPN 2.0 Sample Configuration File
# for PacketiX VPN / SoftEther VPN Server
# 
# !!! AUTO-GENERATED BY SOFTETHER VPN SERVER MANAGEMENT TOOL !!!
# 
# !!! YOU HAVE TO REVIEW IT BEFORE USE AND MODIFY IT AS NECESSARY !!!
# 
# This configuration file is auto-generated. You might use this config file
# in order to connect to the PacketiX VPN / SoftEther VPN Server.
# However, before you try it, you should review the descriptions of the file
# to determine the necessity to modify to suitable for your real environment.
# If necessary, you have to modify a little adequately on the file.
# For example, the IP address or the hostname as a destination VPN Server
# should be confirmed.
# 
# Note that to use OpenVPN 2.0, you have to put the certification file of
# the destination VPN Server on the OpenVPN Client computer when you use this
# config file. Please refer the below descriptions carefully.


###############################################################################
# Specify the type of the layer of the VPN connection.
# 
# To connect to the VPN Server as a "Remote-Access VPN Client PC",
#  specify 'dev tun'. (Layer-3 IP Routing Mode)
#
# To connect to the VPN Server as a bridging equipment of "Site-to-Site VPN",
#  specify 'dev tap'. (Layer-2 Ethernet Bridgine Mode)

dev tun


###############################################################################
# Specify the underlying protocol beyond the Internet.
# Note that this setting must be correspond with the listening setting on
# the VPN Server.
# 
# Specify either 'proto tcp' or 'proto udp'.

proto tcp


###############################################################################
# The destination hostname / IP address, and port number of
# the target VPN Server.
# 
# You have to specify as 'remote <HOSTNAME> <PORT>'. You can also
# specify the IP address instead of the hostname.
# 
# Note that the auto-generated below hostname are a "auto-detected
# IP address" of the VPN Server. You have to confirm the correctness
# beforehand.
# 
# When you want to connect to the VPN Server by using TCP protocol,
# the port number of the destination TCP port should be same as one of
# the available TCP listeners on the VPN Server.
# 
# When you use UDP protocol, the port number must same as the configuration
# setting of "OpenVPN Server Compatible Function" on the VPN Server.

# Note: The below hostname is came from the Dynamic DNS Client function
#       which is running on the VPN Server. If you don't want to use
#       the Dynamic DNS hostname, replace it to either IP address or
#       other domain's hostname.

remote xx.xx.xx.xx 5555


###############################################################################
# The HTTP/HTTPS proxy setting.
# 
# Only if you have to use the Internet via a proxy, uncomment the below
# two lines and specify the proxy address and the port number.
# In the case of using proxy-authentication, refer the OpenVPN manual.

;http-proxy-retry
;http-proxy [proxy server] [proxy port]


###############################################################################
# The encryption and authentication algorithm.
# 
# Default setting is good. Modify it as you prefer.
# When you specify an unsupported algorithm, the error will occur.
# 
# The supported algorithms are as follows:
#  cipher: [NULL-CIPHER] NULL AES-128-CBC AES-192-CBC AES-256-CBC BF-CBC
#          CAST-CBC CAST5-CBC DES-CBC DES-EDE-CBC DES-EDE3-CBC DESX-CBC
#          RC2-40-CBC RC2-64-CBC RC2-CBC
#  auth:   SHA SHA1 MD5 MD4 RMD160

cipher AES-128-CBC
auth SHA1


###############################################################################
# Other parameters necessary to connect to the VPN Server.
# 
# It is not recommended to modify it unless you have a particular need.

resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 3
auth-user-pass


###############################################################################
# The certificate file of the destination VPN Server.
# 
# The CA certificate file is embedded in the inline format.
# You can replace this CA contents if necessary.
# Please note that if the server certificate is not a self-signed, you have to
# specify the signer's root certificate (CA) here.

<ca>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----

</ca>


###############################################################################
# The client certificate file (dummy).
# 
# In some implementations of OpenVPN Client software
# (for example: OpenVPN Client for iOS),
# a pair of client certificate and private key must be included on the
# configuration file due to the limitation of the client.
# So this sample configuration file has a dummy pair of client certificate
# and private key as follows.

<cert>
-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----

</cert>

<key>
-----BEGIN PRIVATE KEY-----

-----END PRIVATE KEY-----

</key>

```

**Comment by schwabe** [comment]
That config looks pretty standard. Try to figure out looking at the log why it is taking so log.

**Comment by batman09** [comment]
Below is the log i observe while I try to connect to VPN. Let me now if there is something that I can skip to achieve < 2s connectivity.



ICS OpenVPN log file - 2017-04-20 00:26:38 official build 0.6.65 running on google Nexus 5 (hammerhead), Android 6.0.1 (M4B30Z) API 23, ABI armeabi-v7a 
2017-04-20 00:26:38 Building configuration…
2017-04-20 00:26:38 New OpenVPN Status (VPN_GENERATE_CONFIG->LEVEL_START): 
2017-04-20 00:26:38 New OpenVPN Status (VPN_GENERATE_CONFIG->LEVEL_START): 
2017-04-20 00:26:38 MANAGEMENT: CMD 'signal SIGINT'
2017-04-20 00:26:38 MANAGEMENT: CMD 'signal SIGINT'
2017-04-20 00:26:38 TCP/UDP: Closing socket
2017-04-20 00:26:38 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2017-04-20 00:26:38 TCP/UDP: Closing socket
2017-04-20 00:26:38 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2017-04-20 00:26:38 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2017-04-20 00:26:38 Closing TUN/TAP interface
2017-04-20 00:26:38 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2017-04-20 00:26:38 Closing TUN/TAP interface
2017-04-20 00:26:38 Debug state info: CONNECTED HSPA+ to MOBILE internet.globe.com.ph, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
2017-04-20 00:26:38 SIGINT[hard,] received, process exiting
2017-04-20 00:26:38 MANAGEMENT: >STATE:1492619198,EXITING,SIGINT,,,,,
2017-04-20 00:26:38 New OpenVPN Status (EXITING->LEVEL_NOTCONNECTED): SIGINT,,,,,
2017-04-20 00:26:38 New OpenVPN Status (EXITING->LEVEL_NOTCONNECTED): SIGINT,,,,,
2017-04-20 00:26:38 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
2017-04-20 00:26:38 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
2017-04-20 00:26:40 SIGINT[hard,] received, process exiting
2017-04-20 00:26:40 Error reading from output of OpenVPN process: OpenVpn process was killed form java code

java.lang.InterruptedException: OpenVpn process was killed form java code
	at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:181)
	at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
	at java.lang.Thread.run(Thread.java:818)

2017-04-20 00:26:40 started Socket Thread
2017-04-20 00:26:40 Network Status: CONNECTED HSPA+ to MOBILE internet.globe.com.ph
2017-04-20 00:26:40 Debug state info: CONNECTED HSPA+ to MOBILE internet.globe.com.ph, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
2017-04-20 00:26:40 P:Initializing Google Breakpad!
2017-04-20 00:26:40 Current Parameter Settings:
2017-04-20 00:26:40   config = '/data/user/0/de.blinkt.openvpn/cache/android.conf'
2017-04-20 00:26:40   mode = 0
2017-04-20 00:26:40   show_ciphers = DISABLED
2017-04-20 00:26:40   show_digests = DISABLED
2017-04-20 00:26:40   show_engines = DISABLED
2017-04-20 00:26:40   genkey = DISABLED
2017-04-20 00:26:40   key_pass_file = '[UNDEF]'
2017-04-20 00:26:40 Waiting 0s seconds between connection attempt
2017-04-20 00:26:40   show_tls_ciphers = DISABLED
2017-04-20 00:26:40   connect_retry_max = 0
2017-04-20 00:26:40 Connection profiles [0]:
2017-04-20 00:26:40   proto = tcp-client
2017-04-20 00:26:40   local = '[UNDEF]'
2017-04-20 00:26:40   local_port = '[UNDEF]'
2017-04-20 00:26:40   remote = 'xx.xx.xx.xx'
2017-04-20 00:26:40   remote_port = '5555'
2017-04-20 00:26:40   remote_float = DISABLED
2017-04-20 00:26:40   bind_defined = DISABLED
2017-04-20 00:26:40   bind_local = DISABLED
2017-04-20 00:26:40   bind_ipv6_only = DISABLED
2017-04-20 00:26:40   connect_retry_seconds = 2
2017-04-20 00:26:40   connect_timeout = 120
2017-04-20 00:26:40   socks_proxy_server = '[UNDEF]'
2017-04-20 00:26:40   socks_proxy_port = '[UNDEF]'
2017-04-20 00:26:40   tun_mtu = 1500
2017-04-20 00:26:40   tun_mtu_defined = ENABLED
2017-04-20 00:26:40   link_mtu = 1500
2017-04-20 00:26:40   link_mtu_defined = DISABLED
2017-04-20 00:26:40   tun_mtu_extra = 0
2017-04-20 00:26:40   tun_mtu_extra_defined = DISABLED
2017-04-20 00:26:40   mtu_discover_type = -1
2017-04-20 00:26:40   fragment = 0
2017-04-20 00:26:40   mssfix = 1450
2017-04-20 00:26:40   explicit_exit_notification = 0
2017-04-20 00:26:40 Connection profiles END
2017-04-20 00:26:40   remote_random = DISABLED
2017-04-20 00:26:40   ipchange = '[UNDEF]'
2017-04-20 00:26:40   dev = 'tun'
2017-04-20 00:26:40   dev_type = '[UNDEF]'
2017-04-20 00:26:40   dev_node = '[UNDEF]'
2017-04-20 00:26:40   lladdr = '[UNDEF]'
2017-04-20 00:26:40   topology = 1
2017-04-20 00:26:40   ifconfig_local = '[UNDEF]'
2017-04-20 00:26:40   ifconfig_remote_netmask = '[UNDEF]'
2017-04-20 00:26:40   ifconfig_noexec = DISABLED
2017-04-20 00:26:40   ifconfig_nowarn = ENABLED
2017-04-20 00:26:40   ifconfig_ipv6_local = '[UNDEF]'
2017-04-20 00:26:40   ifconfig_ipv6_netbits = 0
2017-04-20 00:26:40   ifconfig_ipv6_remote = '[UNDEF]'
2017-04-20 00:26:40   shaper = 0
2017-04-20 00:26:40   mtu_test = 0
2017-04-20 00:26:40   mlock = DISABLED
2017-04-20 00:26:40   keepalive_ping = 0
2017-04-20 00:26:40   keepalive_timeout = 0
2017-04-20 00:26:40   inactivity_timeout = 0
2017-04-20 00:26:40   ping_send_timeout = 0
2017-04-20 00:26:40   ping_rec_timeout = 0
2017-04-20 00:26:40   ping_rec_timeout_action = 0
2017-04-20 00:26:40   ping_timer_remote = DISABLED
2017-04-20 00:26:40   remap_sigusr1 = 0
2017-04-20 00:26:40   persist_tun = ENABLED
2017-04-20 00:26:40   persist_local_ip = DISABLED
2017-04-20 00:26:40   persist_remote_ip = DISABLED
2017-04-20 00:26:40   persist_key = DISABLED
2017-04-20 00:26:40   passtos = DISABLED
2017-04-20 00:26:40   resolve_retry_seconds = 1000000000
2017-04-20 00:26:40   resolve_in_advance = ENABLED
2017-04-20 00:26:40   username = '[UNDEF]'
2017-04-20 00:26:40   groupname = '[UNDEF]'
2017-04-20 00:26:40   chroot_dir = '[UNDEF]'
2017-04-20 00:26:40   cd_dir = '[UNDEF]'
2017-04-20 00:26:40   writepid = '[UNDEF]'
2017-04-20 00:26:40   up_script = '[UNDEF]'
2017-04-20 00:26:40   down_script = '[UNDEF]'
2017-04-20 00:26:40   down_pre = DISABLED
2017-04-20 00:26:40   up_restart = DISABLED
2017-04-20 00:26:40   up_delay = DISABLED
2017-04-20 00:26:40   daemon = DISABLED
2017-04-20 00:26:40   inetd = 0
2017-04-20 00:26:40   log = DISABLED
2017-04-20 00:26:40   suppress_timestamps = DISABLED
2017-04-20 00:26:40   machine_readable_output = ENABLED
2017-04-20 00:26:40   nice = 0
2017-04-20 00:26:40   verbosity = 4
2017-04-20 00:26:40   mute = 0
2017-04-20 00:26:40   gremlin = 0
2017-04-20 00:26:40   status_file = '[UNDEF]'
2017-04-20 00:26:40   status_file_version = 1
2017-04-20 00:26:40   status_file_update_freq = 60
2017-04-20 00:26:40   occ = ENABLED
2017-04-20 00:26:40   rcvbuf = 0
2017-04-20 00:26:40   sndbuf = 0
2017-04-20 00:26:40   sockflags = 0
2017-04-20 00:26:40   fast_io = DISABLED
2017-04-20 00:26:40   comp.alg = 0
2017-04-20 00:26:40   comp.flags = 0
2017-04-20 00:26:40   route_script = '[UNDEF]'
2017-04-20 00:26:40   route_default_gateway = '[UNDEF]'
2017-04-20 00:26:40   route_default_metric = 0
2017-04-20 00:26:40   route_noexec = DISABLED
2017-04-20 00:26:40   route_delay = 0
2017-04-20 00:26:40   route_delay_window = 30
2017-04-20 00:26:40   route_delay_defined = DISABLED
2017-04-20 00:26:40   route_nopull = DISABLED
2017-04-20 00:26:40   route_gateway_via_dhcp = DISABLED
2017-04-20 00:26:40   allow_pull_fqdn = DISABLED
2017-04-20 00:26:40   management_addr = '/data/user/0/de.blinkt.openvpn/cache/mgmtsocket'
2017-04-20 00:26:40   management_port = 'unix'
2017-04-20 00:26:40   management_user_pass = '[UNDEF]'
2017-04-20 00:26:40   management_log_history_cache = 250
2017-04-20 00:26:40   management_echo_buffer_size = 100
2017-04-20 00:26:40   management_write_peer_info_file = '[UNDEF]'
2017-04-20 00:26:40   management_client_user = '[UNDEF]'
2017-04-20 00:26:40   management_client_group = '[UNDEF]'
2017-04-20 00:26:40   management_flags = 4390
2017-04-20 00:26:40   shared_secret_file = '[UNDEF]'
2017-04-20 00:26:40   key_direction = (null)
2017-04-20 00:26:40   ciphername = 'AES-128-CBC'
2017-04-20 00:26:40   ncp_enabled = ENABLED
2017-04-20 00:26:40   ncp_ciphers = 'AES-256-GCM:AES-128-GCM'
2017-04-20 00:26:40   authname = 'SHA1'
2017-04-20 00:26:40   prng_hash = 'SHA1'
2017-04-20 00:26:40   prng_nonce_secret_len = 16
2017-04-20 00:26:40   keysize = 0
2017-04-20 00:26:40   engine = DISABLED
2017-04-20 00:26:40   replay = ENABLED
2017-04-20 00:26:40   mute_replay_warnings = DISABLED
2017-04-20 00:26:40   replay_window = 64
2017-04-20 00:26:40   replay_time = 15
2017-04-20 00:26:40   packet_id_file = '[UNDEF]'
2017-04-20 00:26:40   test_crypto = DISABLED
2017-04-20 00:26:40   tls_server = DISABLED
2017-04-20 00:26:40   tls_client = ENABLED
2017-04-20 00:26:40   key_method = 2
2017-04-20 00:26:40   ca_file = '[[INLINE]]'
2017-04-20 00:26:40   ca_path = '[UNDEF]'
2017-04-20 00:26:40   dh_file = '[UNDEF]'
2017-04-20 00:26:40   cert_file = '[[INLINE]]'
2017-04-20 00:26:40   extra_certs_file = '[UNDEF]'
2017-04-20 00:26:40   priv_key_file = '[[INLINE]]'
2017-04-20 00:26:40   pkcs12_file = '[UNDEF]'
2017-04-20 00:26:40   cipher_list = '[UNDEF]'
2017-04-20 00:26:40   tls_verify = '[UNDEF]'
2017-04-20 00:26:40   tls_export_cert = '[UNDEF]'
2017-04-20 00:26:40   verify_x509_type = 0
2017-04-20 00:26:40   verify_x509_name = '[UNDEF]'
2017-04-20 00:26:40   crl_file = '[UNDEF]'
2017-04-20 00:26:40   ns_cert_type = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_ku[i] = 0
2017-04-20 00:26:40   remote_cert_eku = '[UNDEF]'
2017-04-20 00:26:40   ssl_flags = 0
2017-04-20 00:26:40   tls_timeout = 2
2017-04-20 00:26:40   renegotiate_bytes = -1
2017-04-20 00:26:40   renegotiate_packets = 0
2017-04-20 00:26:40   renegotiate_seconds = 3600
2017-04-20 00:26:40   handshake_window = 60
2017-04-20 00:26:40   transition_window = 3600
2017-04-20 00:26:40   single_session = DISABLED
2017-04-20 00:26:40   push_peer_info = DISABLED
2017-04-20 00:26:40   tls_exit = DISABLED
2017-04-20 00:26:40   tls_auth_file = '[UNDEF]'
2017-04-20 00:26:40   tls_crypt_file = '[UNDEF]'
2017-04-20 00:26:40   client = ENABLED
2017-04-20 00:26:40   pull = ENABLED
2017-04-20 00:26:40   auth_user_pass_file = 'stdin'
2017-04-20 00:26:40 OpenVPN 2.5-icsopenvpn [git:icsopenvpn-5711c5bd3a04f48b] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  4 2017
2017-04-20 00:26:40 library versions: OpenSSL 1.0.2k  26 Jan 2017, LZO 2.09
2017-04-20 00:26:40 MANAGEMENT: Connected to management server at /data/user/0/de.blinkt.openvpn/cache/mgmtsocket
2017-04-20 00:26:40 MANAGEMENT: CMD 'hold release'
2017-04-20 00:26:40 MANAGEMENT: CMD 'username 'Auth' vpn'
2017-04-20 00:26:40 MANAGEMENT: CMD 'bytecount 2'
2017-04-20 00:26:40 MANAGEMENT: CMD 'password [...]'
2017-04-20 00:26:40 MANAGEMENT: CMD 'state on'
2017-04-20 00:26:40 MANAGEMENT: CMD 'proxy NONE'
2017-04-20 00:26:41 New OpenVPN Status (TCP_CONNECT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
2017-04-20 00:26:41 New OpenVPN Status (TCP_CONNECT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
2017-04-20 00:26:41 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
2017-04-20 00:26:41 Control Channel MTU parms [ L:1623 D:1210 EF:40 EB:0 ET:0 EL:3 ]
2017-04-20 00:26:41 Data Channel MTU parms [ L:1623 D:1450 EF:123 EB:406 ET:0 EL:3 ]
2017-04-20 00:26:41 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1559,tun-mtu 1500,proto TCPv4_CLIENT,cipher AES-128-CBC,auth SHA1,keysize 128,key-method 2,tls-client'
2017-04-20 00:26:41 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1559,tun-mtu 1500,proto TCPv4_SERVER,cipher AES-128-CBC,auth SHA1,keysize 128,key-method 2,tls-server'
2017-04-20 00:26:41 TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xx.xx:5555
2017-04-20 00:26:41 Socket Buffers: R=[734003->734003] S=[192239->192239]
2017-04-20 00:26:41 Attempting to establish TCP connection with [AF_INET]xx.xx.xx.xx:5555 [nonblock]
2017-04-20 00:26:41 MANAGEMENT: >STATE:1492619201,TCP_CONNECT,,,,,,
2017-04-20 00:26:41 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2017-04-20 00:26:42 TCP connection established with [AF_INET]xx.xx.xx.xx:5555
2017-04-20 00:26:42 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
2017-04-20 00:26:42 TCP_CLIENT link local: (not bound)
2017-04-20 00:26:42 TCP_CLIENT link remote: [AF_INET]xx.xx.xx.xx:5555
2017-04-20 00:26:42 MANAGEMENT: >STATE:1492619202,WAIT,,,,,,
2017-04-20 00:26:42 New OpenVPN Status (WAIT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
2017-04-20 00:26:42 New OpenVPN Status (WAIT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
2017-04-20 00:26:42 MANAGEMENT: >STATE:1492619202,AUTH,,,,,,
2017-04-20 00:26:42 TLS: Initial packet from [AF_INET]xx.xx.xx.xx:5555, sid=ed4cce9d 028053f3
2017-04-20 00:26:42 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2017-04-20 00:26:42 New OpenVPN Status (AUTH->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
2017-04-20 00:26:42 New OpenVPN Status (AUTH->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
2017-04-20 00:26:43 VERIFY OK: depth=0, CN=coreappdev01, O=coreappdev01, OU=coreappdev01, C=US
2017-04-20 00:26:43 Control Channel: TLSv1.2, cipher TLSv1/SSLv3 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
2017-04-20 00:26:43 [coreappdev01] Peer Connection Initiated with [AF_INET]xx.xx.xx.xx:5555
2017-04-20 00:26:44 New OpenVPN Status (GET_CONFIG->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
2017-04-20 00:26:44 New OpenVPN Status (GET_CONFIG->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
2017-04-20 00:26:44 MANAGEMENT: >STATE:1492619204,GET_CONFIG,,,,,,
2017-04-20 00:26:44 SENT CONTROL [coreappdev01]: 'PUSH_REQUEST' (status=1)
2017-04-20 00:26:45 PUSH: Received control message: 'PUSH_REPLY,ping 3,ping-restart 10,ifconfig 192.168.30.13 192.168.30.14,dhcp-option DNS 192.168.30.1,route-gateway 192.168.30.14,redirect-gateway def1'
2017-04-20 00:26:45 OPTIONS IMPORT: timers and/or timeouts modified
2017-04-20 00:26:45 OPTIONS IMPORT: --ifconfig/up options modified
2017-04-20 00:26:45 New OpenVPN Status (ASSIGN_IP->LEVEL_CONNECTING_SERVER_REPLIED): ,192.168.30.13,,,,
2017-04-20 00:26:45 New OpenVPN Status (ASSIGN_IP->LEVEL_CONNECTING_SERVER_REPLIED): ,192.168.30.13,,,,
2017-04-20 00:26:45 OPTIONS IMPORT: route options modified
2017-04-20 00:26:45 OPTIONS IMPORT: route-related options modified
2017-04-20 00:26:45 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
2017-04-20 00:26:45 Data Channel MTU parms [ L:1559 D:1450 EF:59 EB:406 ET:0 EL:3 ]
2017-04-20 00:26:45 Data Channel Encrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
2017-04-20 00:26:45 Data Channel Encrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
2017-04-20 00:26:45 Data Channel Decrypt: Cipher 'AES-128-CBC' initialized with 128 bit key
2017-04-20 00:26:45 Data Channel Decrypt: Using 160 bit message hash 'SHA1' for HMAC authentication
2017-04-20 00:26:45 GDG: SIOCGIFHWADDR(lo) failed
2017-04-20 00:26:45 ROUTE_GATEWAY 127.100.103.119/255.0.0.0 IFACE=lo
2017-04-20 00:26:45 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
2017-04-20 00:26:45 MANAGEMENT: >STATE:1492619205,ASSIGN_IP,,192.168.30.13,,,,
2017-04-20 00:26:45 MANAGEMENT: CMD 'needok 'IFCONFIG' ok'
2017-04-20 00:26:45 MANAGEMENT: CMD 'needok 'ROUTE' ok'
2017-04-20 00:26:45 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
2017-04-20 00:26:45 MANAGEMENT: CMD 'needok 'PERSIST_TUN_ACTION' OPEN_BEFORE_CLOSE'
2017-04-20 00:26:45 Opening tun interface:
2017-04-20 00:26:45 Local IPv4: 192.168.30.13/30 IPv6: null MTU: 1500
2017-04-20 00:26:45 DNS Server: 192.168.30.1, Domain: null
2017-04-20 00:26:45 Routes: 0.0.0.0/0, 192.168.30.12/30 
2017-04-20 00:26:45 Routes excluded:  
2017-04-20 00:26:45 VpnService routes installed: 0.0.0.0/0 
2017-04-20 00:26:45 Disallowed VPN apps: 
2017-04-20 00:26:45 MANAGEMENT: CMD 'needok 'OPENTUN' ok'
2017-04-20 00:26:45 Initialization Sequence Completed
2017-04-20 00:26:45 MANAGEMENT: >STATE:1492619205,CONNECTED,SUCCESS,192.168.30.13,xx.xx.xx.xx,5555,100.107.229.114,58782
2017-04-20 00:26:45 New OpenVPN Status (CONNECTED->LEVEL_CONNECTED): SUCCESS,192.168.30.13,xx.xx.xx.xx,5555,100.107.229.114,58782
2017-04-20 00:26:45 New OpenVPN Status (CONNECTED->LEVEL_CONNECTED): SUCCESS,192.168.30.13,xx.xx.xx.xx,5555,100.107.229.114,58782

**Comment by schwabe** [comment]
Am 19.04.17 um 18:40 schrieb new:
> Below is the log i observe while I try to connect to VPN. Let me now if
> there is something that I can skip to achieve < 2s connectivity.

not sure try the tcp-nodelay option or changing to udp and see if that
makes a difference.

Arne

**Comment by batman09** [comment]
Ok. I will check on that.

**Comment by schwabe** [comment]
no response
