### ISSUE TITLE
java.lang.RuntimeException—NullPointerException on CRL selection

### ISSUE THREAD

**Issue by asiplas** [schwabe/ics-openvpn#660]
**Android** 7.1.2
**Vendor** Google (built by wpds8.hot.corp.google.com)
**Device** Nexus—Angler
**de.blinkt.openvpn** 0.6.63 (*update: also present with on master/3f28653*)

# Details
*I'm checking out the latest source now; the following occurs with 0.6.63 from F-Droid Repo.*
**Update: Present on master/3f28653 – seems to be issue where not waiting for permissions—see comment**

After a CRL expiration, I enter the 'Basic' settings tab for existing VPN and find myself with a runtime exception the precludes updating the CRL.

After clicking 'Select' button next to 'Certificate Revoke List' (where one has already been imported, but  has expired), application crashes with the following:

## Exception

`04-24 12:39:15.622 28112-28112/? E/AndroidRuntime: FATAL EXCEPTION: main`
`Process: de.blinkt.openvpn, PID: 28112`
`java.lang.RuntimeException: Unable to start activity ComponentInfo{de.blinkt.openvpn/de.blinkt.openvpn.activities.FileSelect}: java.lang.NullPointerException: Attempt to get length of null array`
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6121)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`Caused by: java.lang.NullPointerException: Attempt to get length of null array`
    at de.blinkt.openvpn.fragments.FileSelectionFragment.getDirImpl(FileSelectionFragment.java:196)
    at de.blinkt.openvpn.fragments.FileSelectionFragment.getDir(FileSelectionFragment.java:148)
    at de.blinkt.openvpn.fragments.FileSelectionFragment.onActivityCreated(FileSelectionFragment.java:133)
    at android.app.Fragment.performActivityCreated(Fragment.java:2362)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1014)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    at android.app.BackStackRecord.run(BackStackRecord.java:816)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
    at android.app.FragmentController.execPendingActions(FragmentController.java:371)
    at android.app.Activity.performStart(Activity.java:6698)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2629)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.app.ActivityThread.main(ActivityThread.java:6121) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by asiplas** [comment]
After fresh install from latest sources, this still occurs… seemingly not waiting for permission;  App crashes with Permission Dialog present under the app crash message.

Upon granting permission and restarting, all is well, however.
