### ISSUE TITLE
FATAL EXCEPTION when install in /System/App

### ISSUE THREAD

**Issue by adahary** [schwabe/ics-openvpn#662]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version: 6.0
2. Android Vendor: DOOGEE
3. Device: X5max_pro
4. Version of the app: ics-openvpn-master self built
 
# Description of the issue
I've built and signed up normalRelease.apk (I've extracted the assets & libs from the latest apk).

I installed the normalRelease.apk in the /system/app, rebooted, opened it, provided permissions and imported an ovpn file profile which got listed in the profile pane properly.

The problem occurs when trying to connect with the selected profile - then the app crashes with the following:
04-26 11:13:45.782 3327-3341/? E/AndroidRuntime: FATAL EXCEPTION: Thread-254
                                                 Process: de.blinkt.openvpn:openvpn, PID: 3327
                                                 java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
                                                     at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:293)
                                                     at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:685)
                                                     at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:482)
                                                     at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:64)
                                                     at de.blinkt.openvpn.core.OpenVPNService$3.run(OpenVPNService.java:457)
                                                     at java.lang.Thread.run(Thread.java:818)

There is no problem when the apk is installed normally (not in the /system/app).

Is there any required modifications for installing this apk as a system app?

Regards

Assaf

**Comment by schwabe** [comment]
I have absolutly no idea, I never tried installing it as system app. Does logcat give any indications? 

Also your way of installing might be not complete, just copying the apk is probably not enough as normal apk install also extracts the libraries.

**Comment by adahary** [comment]
You've just provided the solution by indicating that NORMAL apk installation extracts the libraries which surely was missing (java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils).

Eventually, I put the apk in the /system/app, then installed with 'pm install apk' (that handled the libs) and finally rebooted to add the apk to register the apk in the system partition. 

Thanks

Assaf

**Comment by schwabe** [comment]
Glad that it worked.
