### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by cnsms** [schwabe/ics-openvpn#713]
2017-07-04 18:03:06 由 C=US,O=Android,CN=Android Debug 构建 0.6.73 running on Xiaomi MI 5s (msm8996), Android 6.0.1 (MXB48T) API 23, ABI arm64-v8a, (Xiaomi/capricorn/capricorn:6.0.1/MXB48T/7.5.11:user/release-keys)
2017-07-04 18:03:06 Building configuration…
2017-07-04 18:03:06 New OpenVPN Status (VPN_GENERATE_CONFIG->LEVEL_START): 
2017-07-04 18:03:06 New OpenVPN Status (VPN_GENERATE_CONFIG->LEVEL_START): 
2017-07-04 18:03:06 Failed getting assets for archicture arm64-v8a
2017-07-04 18:03:06 Failed getting assets for archicture armeabi-v7a
2017-07-04 18:03:06 Failed getting assets for archicture armeabi
2017-07-04 18:03:06 Error writing minivpn binary
2017-07-04 18:03:06 started Socket Thread
2017-07-04 18:03:06 Starting OpenVPN Thread: Attempt to get length of null array

java.lang.NullPointerException: Attempt to get length of null array
	at java.util.Collections.addAll(Collections.java:2604)
	at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:122)
	at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
	at java.lang.Thread.run(Thread.java:818)

2017-07-04 18:03:06 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
2017-07-04 18:03:06 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
2017-07-04 18:03:06 Network Status: CONNECTED  to WIFI "亚健医疗-5G"
2017-07-04 18:03:06 Debug state info: CONNECTED  to WIFI "亚健医疗-5G", pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
2017-07-04 18:03:06 Debug state info: CONNECTED  to WIFI "亚健医疗-5G", pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED

**Comment by schwabe** [comment]
You failed to read the doc/README how to build this app.
