### ISSUE TITLE
Error on New Profile 

### ISSUE THREAD

**Issue by roconmachine** [schwabe/ics-openvpn#789]
I compiled and ran the source code, application lunched successfully but on tap of New Profile i got an error every time is below

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.blinkt.openvpn.remote, PID: 32433
                  java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
                      at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:277)
                      at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:265)
                      at android.view.View.performClick(View.java:5207)
                      at android.view.View$PerformClick.run(View.java:21177)
                      at android.os.Handler.handleCallback(Handler.java:742)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:5529)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
E/MQSEventManagerDelegate: failed to get MQSService.

**Comment by schwabe** [comment]
Something is very wrong with your build. That menas that you somehow broke the app's ability to start its service

**Comment by schwabe** [comment]
Did you modify the app in any way before building? Also that trace looks like starting a VPN and not "new profile"

**Comment by Jay268** [comment]
@schwabe I am also getting the same issue.

Here is the log.

`11-27 17:19:48.307 28294-28294/de.blinkt.openvpn.remote E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: de.blinkt.openvpn.remote, PID: 28294
                                                                          java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
                                                                              at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:277)
                                                                              at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:265)
                                                                              at android.view.View.performClick(View.java:5612)
                                                                              at android.view.View$PerformClick.run(View.java:22285)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

I didn't modified anything in the app. When i build and started ran app on Add New Profile click it is getting crashed with above exception.

@schwabe Can you have a look into it.

**Comment by schwabe** [comment]
@Jay268 as I said, check your log(cat) why the service does not start.

**Comment by Jay268** [comment]
@schwabe The above posted comment itself is copied form log(cat) and on first ran it crashed with this much information inside it. Do i need to make any configuration file changes ? My requirement is that i need to import .ovpn profile having with me and after importing i need to authenticate with username password specifically with using OpenVPN. Can you suggest me the changes of configuration file if any ?

**Comment by schwabe** [comment]
Do you have the normal already installed? The remoteExample assumes the normal app to be there. It does not have the checks if the app is really installed.

**Comment by Jay268** [comment]
@schwabe Do you mean that OpenVPN for Android normal app should be installed on my device ?

**Comment by schwabe** [comment]
The trace is coming from the remoteExample app, which job is to show how you can use the normal app to start/add a config to that. And therefore it needs the normal app, yes.

**Comment by Jay268** [comment]
@schwabe I installed normal app and i got an attention for trust the application and i do accept it. But then now when i click on any of the Add new Profile , Start embedded profile , Show my IP it just showing no process running message at top nothing happens. What should i do if i need to import my .ovpn profile from remoteExample app and do authentication from same ? can you suggest me ?

**Comment by schwabe** [comment]
The profiles that are included in the remoteExample are not working. They serve only as example how you would include your own profile.

**Comment by uemscit2014** [comment]
hey , m getting the same error , when i click on Add new profile , app crashes . Please help me. log cat info is given below.

```12-27 05:36:54.651 14537-14537/de.blinkt.openvpn.remote W/IInputConnectionWrapper: getExtractedText on inactive InputConnection
12-27 05:36:54.652 14537-14537/de.blinkt.openvpn.remote W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
12-27 05:36:54.652 14537-14537/de.blinkt.openvpn.remote W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
12-27 05:36:54.653 14537-14537/de.blinkt.openvpn.remote W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
12-27 05:36:55.698 14537-14537/de.blinkt.openvpn.remote I/hwaps: JNI_OnLoad
12-27 05:36:55.812 14537-14537/de.blinkt.openvpn.remote E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: de.blinkt.openvpn.remote, PID: 14537
                                                                          java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
                                                                              at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:277)
                                                                              at de.blinkt.openvpn.remote.MainFragment.onClick(MainFragment.java:265)
                                                                              at android.view.View.performClick(View.java:5646)
                                                                              at android.view.View$PerformClick.run(View.java:22459)
                                                                              at android.os.Handler.handleCallback(Handler.java:761)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
12-27 05:36:55.835 14537-14537/de.blinkt.openvpn.remote I/Process: Sending signal. PID: 14537 SIG: 9```

**Comment by xiaoa7** [comment]
我也遇到了这个问题。
发现部分android手机是可以正常运行的。
LG、小米运行正常；
魅族 pro6 就出下面的错误：
 java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference

**Comment by AjmalPL** [comment]
Is it resolved ? I am also getting the same error. The service is not binding.
The project was working very fine about 4 months back. Now when i reopened the project , The service doesn't start and the bindService returns false.

**Comment by schwabe** [comment]
Please open a new issue, this issue already mixes at least to different problems.

**Comment by Deepanshusuman** [comment]
I am also waiting for this reply
i am getting this 
```
Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
```

**Comment by PrarthanaBhatt** [comment]
I'm getting this,  

 Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference

**Comment by schwabe** [comment]
@PrarthanaBhatt Without context. I have no idea. Look at the remote example how to correctly use the external API. And alos wrong issue.
