### ISSUE TITLE
Exception after confirming the trust message

### ISSUE THREAD

**Issue by Abu-Abdullah** [schwabe/ics-openvpn#806]
Hi,

I'm receiving the following exception once i confirm that attention message to trust the app
 
```
E/WindowManager: android.view.WindowLeaked: Activity de.blinkt.openvpn.api.ConfirmDialog has leaked window DecorView@4466d23[] that was originally added here
	  at android.view.ViewRootImpl.<init>(ViewRootImpl.java:484)
	  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:360)
	  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
	  at android.app.Dialog.show(Dialog.java:440)
	  at de.blinkt.openvpn.api.ConfirmDialog.onResume(ConfirmDialog.java:89)
	  at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1279)
	  at android.app.Activity.performResume(Activity.java:7017)
	  at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3561)
	  at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3626)
	  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2876)
	  at android.app.ActivityThread.-wrap12(ActivityThread.java)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
	  at android.os.Handler.dispatchMessage(Handler.java:105)
	  at android.os.Looper.loop(Looper.java:156)
	  at android.app.ActivityThread.main(ActivityThread.java:6523)
	  at java.lang.reflect.Method.invoke(Native Method)
	  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by schwabe** [comment]
I think this is only a warning . Also the leaked window is inside Dialog, i.e. Android's own code.
