### ISSUE TITLE
OVPN Process was killed from java code 

### ISSUE THREAD

**Issue by javaerror** [schwabe/ics-openvpn#845]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 5
2. Android Vendor/Custom ROM fireOS
3. Device fire kindle
4. Version of the app (version number/play store version/self-built)7.3.1
 
# Description of the issue
`09:37 Error reading from output of OpenVPN process: OpenVpn process was killed form java code

java.lang.InterruptedException: OpenVpn process was killed form java code
	at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:188)
	at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
	at java.lang.Thread.run(Thread.java:818)
`
Happened while whatching Videos on youtu. So far it worked well since that happened.

**Comment by schwabe** [comment]
Do you have a more complete log? Or steps how to reproduce this. I never have seen anything like

**Comment by javaerror** [comment]
Today the error occured again. Only browser open without opening a site. I know that I am running out of mem from time to time but that is another entry in the ovpn-protocol. So now here is a more complete log. Please be patient, I'm not into this whole developer thing.


```
14:28 MANAGEMENT: >STATE:1520256517,CONNECTED,SUCCESS,10.8.8.12,82.102.20.238,1194,,
15:25 [dk27.nordvpn.com] Inactivity timeout (--ping-restart), restarting
15:25 MANAGEMENT: >STATE:1520259913,RECONNECTING,ping-restart,,,,,
15:25 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
15:25 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
15:25 TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.20.238:1194
15:25 Socket Buffers: R=[163840->1048576] S=[163840->327680]
15:25 UDP link local: (not bound)
15:25 UDP link remote: [AF_INET]82.102.20.238:1194
15:25 MANAGEMENT: >STATE:1520259916,WAIT,,,,,,
15:25 MANAGEMENT: >STATE:1520259917,AUTH,,,,,,
15:25 TLS: Initial packet from [AF_INET]82.102.20.238:1194, sid=
15:25 VERIFY OK: depth=1, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=vpn.com, name=VPN, emailAddress=cert@
15:25 VERIFY KU OK
15:25 Validating certificate extended key usage
15:25 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
15:25 VERIFY EKU OK
15:25 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=VPN, CN=vpn.com, name=VPN, emailAddress=cert@
15:25 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1582', remote='link-mtu 1634'
15:25 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-256-CBC'
15:25 WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA512'
15:25 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
15:25 [vpn.com] Peer Connection Initiated with [AF_INET]82.:1194
15:25 MANAGEMENT: >STATE:1520259919,GET_CONFIG,,,,,,
15:25 SENT CONTROL [vpn.com]: 'PUSH_REQUEST' (status=1)
15:25 SENT CONTROL [vpn.com]: 'PUSH_REQUEST' (status=1)
15:25 SENT CONTROL [vpn.com]: 'PUSH_REQUEST' (status=1)
15:25 Generiere OpenVPN-Konfiguration…
15:25 SIGTERM received, sending exit notification to peer
15:25 started Socket Thread
15:25 Netzwerkstatus: CONNECTED  to WIFI FRITZ!Box 7330
15:25 P:WARNING: linker: /data/data/de.blinkt.openvpn/cache/c_pie_openvpn.armeabi-v7a: unused DT entry: type 0x6ffffffe arg 0x318
15:25 P:WARNING: linker: /data/data/de.blinkt.openvpn/cache/c_pie_openvpn.armeabi-v7a: unused DT entry: type 0x6fffffff arg 0x1
15:25 P:WARNING: linker: libopenvpn.so: unused DT entry: type 0x6ffffffe arg 0x3e330
15:25 P:WARNING: linker: libopenvpn.so: unused DT entry: type 0x6fffffff arg 0x2
15:25 SENT CONTROL [dvpn.com]: 'PUSH_REQUEST' (status=1)
15:25 Error reading from output of OpenVPN process: OpenVpn process was killed form java code
java.lang.InterruptedException: OpenVpn process was killed form java code
	at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:188)
	at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
	at java.lang.Thread.run(Thread.java:818)
15:25 Process exited with exit value 9
15:25 OpenVPN 2.5-icsopenvpn [git:icsopenvpn_703-0-ge375db48] armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan 31 2018
15:25 library versions: OpenSSL 1.1.0g  2 Nov 2017, LZO 2.10
15:25 MANAGEMENT: Connected to management server at /data/data/de.blinkt.openvpn/cache/mgmtsocket
15:25 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,sndbuf 524288,rcvbuf 524288,dhcp-option DNS 78,dhcp-option DNS 37,dhcp-option DNS 10,dhcp-option DNS 10,route-gateway 10.8.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.8.9 255.255.255.0,peer-id 22,cipher AES-256-GCM'
```
If you need the full protocol  (level 4) I hope the program kept it. Otherwise I will post when the error occured again.

**Comment by javaerror** [comment]
```
15:25 [dk27.nordvpn.com] Inactivity timeout (--ping-restart), restarting
15:25 TCP/UDP: Closing socket
15:25 SIGUSR1[soft,ping-restart] received, process restarting
15:25 MANAGEMENT: >STATE:1520259913,RECONNECTING,ping-restart,,,,,
15:25 New OpenVPN Status (RECONNECTING->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ping-restart,,,,,
15:25 New OpenVPN Status (CONNECTRETRY->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): 2
15:25 Warte 2s Sekunden zwischen zwei Verbindungsversuchen
15:25 MANAGEMENT: CMD 'hold release'
15:25 MANAGEMENT: CMD 'proxy NONE'
15:25 MANAGEMENT: CMD 'bytecount 2'
15:25 MANAGEMENT: CMD 'state on'
15:25 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
15:25 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
15:25 LZO compression initializing
15:25 Control Channel MTU parms [ L:1654 D:1140 EF:110 EB:0 ET:0 EL:3 ]
15:25 Data Channel MTU parms [ L:1654 D:1450 EF:122 EB:411 ET:32 EL:3 ]
15:25 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1582,tun-mtu 1532,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-GCM,auth [null-digest],keysize 256,tls-auth,key-method 2,tls-client'
15:25 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1582,tun-mtu 1532,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-GCM,auth [null-digest],keysize 256,tls-auth,key-method 2,tls-server'
15:25 TCP/UDP: Preserving recently used remote address: [AF_INET]82.102.20.238:1194
15:25 Socket Buffers: R=[163840->1048576] S=[163840->327680]
15:25 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
15:25 UDP link local: (not bound)
15:25 UDP link remote: [AF_INET]82.102.20.238:1194
15:25 New OpenVPN Status (WAIT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
15:25 MANAGEMENT: >STATE:1520259916,WAIT,,,,,,
15:25 MANAGEMENT: >STATE:1520259917,AUTH,,,,,,
15:25 New OpenVPN Status (AUTH->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
15:25 TLS: Initial packet from [AF_INET]82.102.20.238:1194, sid=b9f70884 1e875f1e
15:25 VERIFY OK: depth=1, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=dk27.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
15:25 VERIFY KU OK
15:25 Validating certificate extended key usage
15:25 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
15:25 VERIFY EKU OK
15:25 VERIFY OK: depth=0, C=PA, ST=PA, L=Panama, O=NordVPN, OU=NordVPN, CN=dk27.nordvpn.com, name=NordVPN, emailAddress=cert@nordvpn.com
15:25 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1582', remote='link-mtu 1634'
15:25 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-GCM', remote='cipher AES-256-CBC'
15:25 WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA512'
15:25 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
15:25 [dk27.nordvpn.com] Peer Connection Initiated with [AF_INET]82.102.20.238:1194
15:25 MANAGEMENT: >STATE:1520259919,GET_CONFIG,,,,,,
15:25 SENT CONTROL [dk27.nordvpn.com]: 'PUSH_REQUEST' (status=1)
15:25 New OpenVPN Status (GET_CONFIG->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
15:25 SENT CONTROL [dk27.nordvpn.com]: 'PUSH_REQUEST' (status=1)
15:25 SENT CONTROL [dk27.nordvpn.com]: 'PUSH_REQUEST' (status=1)
15:25 Generiere OpenVPN-Konfiguration…
15:25 New OpenVPN Status (VPN_GENERATE_CONFIG->LEVEL_START): 
15:25 New OpenVPN Status (VPN_GENERATE_CONFIG->LEVEL_START): 
15:25 MANAGEMENT: CMD 'signal SIGINT'
15:25 SIGTERM received, sending exit notification to peer
15:25 started Socket Thread
15:25 Netzwerkstatus: CONNECTED  to WIFI FRITZ!Box 7330
15:25 Debug state info: CONNECTED  to WIFI FRITZ!Box 7330, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
15:25 Debug state info: CONNECTED  to WIFI FRITZ!Box 7330, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
15:25 P:WARNING: linker: /data/data/de.blinkt.openvpn/cache/c_pie_openvpn.armeabi-v7a: unused DT entry: type 0x6ffffffe arg 0x318
15:25 P:WARNING: linker: /data/data/de.blinkt.openvpn/cache/c_pie_openvpn.armeabi-v7a: unused DT entry: type 0x6fffffff arg 0x1
15:25 P:WARNING: linker: libopenvpn.so: unused DT entry: type 0x6ffffffe arg 0x3e330
15:25 P:WARNING: linker: libopenvpn.so: unused DT entry: type 0x6fffffff arg 0x2
15:25 Current Parameter Settings:
15:25   config = '/data/data/de.blinkt.openvpn/cache/android.conf'
15:25   mode = 0
15:25   show_ciphers = DISABLED
15:25   show_digests = DISABLED
15:25   show_engines = DISABLED
15:25   genkey = DISABLED
15:25 Warte 0s Sekunden zwischen zwei Verbindungsversuchen
15:25   key_pass_file = '[UNDEF]'
15:25   show_tls_ciphers = DISABLED
15:25   connect_retry_max = 0
15:25 Connection profiles [0]:
15:25   proto = udp
15:25   local = '[UNDEF]'
15:25   local_port = '[UNDEF]'
15:25   remote_float = DISABLED
15:25   bind_defined = DISABLED
15:25   bind_local = DISABLED
15:25 SENT CONTROL [dk27.nordvpn.com]: 'PUSH_REQUEST' (status=1)
15:25   bind_ipv6_only = DISABLED
15:25   connect_retry_seconds = 2
15:25   connect_timeout = 120
15:25 Error reading from output of OpenVPN process: OpenVpn process was killed form java code

java.lang.InterruptedException: OpenVpn process was killed form java code
	at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:188)
	at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:64)
	at java.lang.Thread.run(Thread.java:818)
15:25   socks_proxy_server = '[UNDEF]'
15:25   socks_proxy_port = '[UNDEF]'
15:25   tun_mtu = 1500
15:25   tun_mtu_defined = ENABLED
15:25   link_mtu = 1500

```
The more complete

**Comment by schwabe** [comment]
That looks like the connection was shutdown on purpose:

15:25 MANAGEMENT: CMD 'signal SIGINT'

This only happens if the user stops the service or if the device asks openvpn to stop. Maybe RAM pressure? Is that a kindle with a small amount of RAM?
