### ISSUE TITLE
Firestick OpenVPN error

### ISSUE THREAD

**Issue by HarvsG** [schwabe/ics-openvpn#875]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
Amazon 
3. Device
Firestick Gen 1
4. Version of the app (version number/play store version/self-built)
2.1.0
 
# Description of the issue
When I try to run the add on I simply get "OpenVPN error"
```
18:32:16.046 T:1411554704   DEBUG: CPythonInvoker(20, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openvpn/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openvpn
18:32:16.047 T:1411554704   DEBUG: CPythonInvoker(20, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openvpn/default.py): instantiating addon using automatically obtained id of "script.openvpn" dependent on version 2.1.0 of the xbmc.python api
18:32:16.428 T:1411554704   DEBUG: script.openvpn: DEBUG: Addon Id:   [script.openvpn]
18:32:16.428 T:1411554704   DEBUG: script.openvpn: DEBUG: Addon Name: [OpenVPN]
18:32:16.429 T:1411554704   DEBUG: script.openvpn: DEBUG: Version:    [2.1.0]
18:32:16.429 T:1411554704   DEBUG: script.openvpn: DEBUG: OpenVPN:    [/usr/bin/openvpn]
18:32:16.430 T:1411554704   DEBUG: script.openvpn: DEBUG: Userdata:   [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.openvpn/]
18:32:16.430 T:1411554704   DEBUG: script.openvpn: DEBUG: OpenVPN Management Interface IP: [127.0.0.1]
18:32:16.430 T:1411554704   DEBUG: script.openvpn: DEBUG: OpenVPN Management Interface Port: [25430]
18:32:16.431 T:1411554704   DEBUG: script.openvpn: DEBUG: OpenVPN Additional Arguments: []
18:32:16.431 T:1411554704   DEBUG: script.openvpn: DEBUG: Sudo: [False]
18:32:16.432 T:1411554704   DEBUG: script.openvpn: DEBUG: Found configuration: [Firestick.ovpn]
18:32:16.433 T:1411554704   DEBUG: script.openvpn: DEBUG: Found configuration: [do.ovpn]
18:32:16.434 T:1411554704   DEBUG: script.openvpn: DEBUG: Response from is_running: [False] [None] [None]
18:32:16.452 T:1106989496   DEBUG: ------ Window Init (DialogSelect.xml) ------
18:32:18.170 T:1106989496   DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
18:32:18.326 T:1106989496   DEBUG: OnKey: return (0xf00d) pressed, action is Select
18:32:18.327 T:1106989496   DEBUG: Keyboard: scancode: 0x17, sym: 0x000d, unicode: 0x0000, modifier: 0x0
18:32:18.603 T:1106989496   DEBUG: ------ Window Deinit (DialogSelect.xml) ------
18:32:18.629 T:1411554704   DEBUG: script.openvpn: DEBUG: Select: [Firestick.ovpn]
18:32:18.630 T:1411554704   DEBUG: script.openvpn: DEBUG: Connecting OpenVPN configuration: [Firestick.ovpn]
18:32:18.631 T:1411554704   DEBUG: OpenVPN: DEBUG: OpenVPN: [/usr/bin/openvpn]
18:32:18.631 T:1411554704   DEBUG: OpenVPN: DEBUG: OpenVPN Configuration: [/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.openvpn/Firestick.ovpn]
18:32:18.631 T:1411554704   DEBUG: OpenVPN: DEBUG: OpenVPN Management IP: [127.0.0.1]
18:32:18.632 T:1411554704   DEBUG: OpenVPN: DEBUG: OpenVPN Management Port: [25430]
18:32:18.632 T:1411554704   DEBUG: OpenVPN: DEBUG: Additional Arguments: []
18:32:18.632 T:1411554704   DEBUG: OpenVPN: ERROR: OpenVPN: ERROR: Specified OpenVPN does not exist
18:32:18.634 T:1411554704   DEBUG: OpenVPN: DEBUG: Connecting OpenVPN
18:32:18.636 T:1411554704   DEBUG: OpenVPN: DEBUG: [Errno 111] Connection refused
18:32:18.636 T:1411554704   DEBUG: OpenVPN: DEBUG: Command line: ['/usr/bin/openvpn' --cd '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.openvpn' --daemon --management 127.0.0.1 25430 --config '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.openvpn/Firestick.ovpn' --log '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/script.openvpn/openvpn.log' ]
18:32:18.708 T:1411554704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openvpn/default.py", line 263, in <module>
                                                connect_openvpn(ovpn)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openvpn/default.py", line 145, in connect_openvpn
                                                openvpn.connect()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.openvpn/resources/lib/openvpn.py", line 205, in connect
                                                stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/subprocess.py", line 711, in __init__
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/subprocess.py", line 1343, in _execute_child
                                            OSError: [Errno 2] No such file or directory
                                            -->End of Python script error report<--
18:32:18.724 T:1106989496   DEBUG: ------ Window Init (DialogNotification.xml) ------
18:32:18.786 T:1411554704    INFO: Python script stopped
18:32:18.786 T:1411554704   DEBUG: Thread LanguageInvoker 1411554704 terminating
18:32:24.475 T:1106989496   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

```
note the `/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/subprocess.py`, `jenkins` is not a name I recognise

**Comment by schwabe** [comment]
```
18:32:16.428 T:1411554704   DEBUG: script.openvpn: DEBUG: Addon Name: [OpenVPN]
18:32:16.429 T:1411554704   DEBUG: script.openvpn: DEBUG: Version:    [2.1.0]
```

That seem to be an openvpn addon not my app. I have no idea what it is doing. I

**Comment by HarvsG** [comment]
Apologies, wrong repo. I will close and delete at a later date (when you have seen this apology)
